CREATE TABLE [AssessmentModule].[PsychologicalHistory] (
    [PsychologicalHistoryKey]                                                        BIGINT         NOT NULL,
    [Version]                                                                        INT            NOT NULL,
    [CantWaitForThingsWantedBadly]                                                   BIT            NULL,
    [DifficultToWorkNowForFutureGain]                                                BIT            NULL,
    [MedicatedForPsychologicalEmotionalProblemInLast24Hours]                         BIT            NULL,
    [MedicatedForPsychologicalEmotionalProblemInLastMonth]                           BIT            NULL,
    [MedicatedForPsychologicalEmotionalProblemInLifetime]                            BIT            NULL,
    [NumberOfDaysExperiencedPsychologicalEmotionalProblemsInLast30Days]              BIGINT         NULL,
    [ReceivesPensionForPsychiatricDisability]                                        BIT            NULL,
    [TimesTreatedForPsychologicalOrEmotionalProblemsAsOutpatient]                    BIGINT         NULL,
    [TimesTreatedForPsychologicalOrEmotionalProblemsInHospital]                      BIGINT         NULL,
    [IsVisited]                                                                      BIT            NOT NULL,
    [AnxietyAttackChestPainsInLast24HoursCode]                                       NVARCHAR (200) NULL,
    [AnxietyAttackChestPainsInLast24HoursName]                                       NVARCHAR (200) NULL,
    [AnxietyAttackChestPainsInLast24HoursValue]                                      INT            NULL,
    [AnxietyAttackChestPainsInLast24HoursIsDefault]                                  BIT            NULL,
    [AnxietyAttackChestPainsInLast24HoursSortOrder]                                  INT            NULL,
    [AnxietyAttackChestPainsInLastMonthCode]                                         NVARCHAR (200) NULL,
    [AnxietyAttackChestPainsInLastMonthName]                                         NVARCHAR (200) NULL,
    [AnxietyAttackChestPainsInLastMonthValue]                                        INT            NULL,
    [AnxietyAttackChestPainsInLastMonthIsDefault]                                    BIT            NULL,
    [AnxietyAttackChestPainsInLastMonthSortOrder]                                    INT            NULL,
    [AnxietyAttackChestPainsInLifetimeCode]                                          NVARCHAR (200) NULL,
    [AnxietyAttackChestPainsInLifetimeName]                                          NVARCHAR (200) NULL,
    [AnxietyAttackChestPainsInLifetimeValue]                                         INT            NULL,
    [AnxietyAttackChestPainsInLifetimeIsDefault]                                     BIT            NULL,
    [AnxietyAttackChestPainsInLifetimeSortOrder]                                     INT            NULL,
    [AnxietyAttackChestPainsRelatedToSubstanceUseCode]                               NVARCHAR (200) NULL,
    [AnxietyAttackChestPainsRelatedToSubstanceUseName]                               NVARCHAR (200) NULL,
    [AnxietyAttackChestPainsRelatedToSubstanceUseValue]                              INT            NULL,
    [AnxietyAttackChestPainsRelatedToSubstanceUseIsDefault]                          BIT            NULL,
    [AnxietyAttackChestPainsRelatedToSubstanceUseSortOrder]                          INT            NULL,
    [AnxietyAttackChillsHotFlashesInLast24HoursCode]                                 NVARCHAR (200) NULL,
    [AnxietyAttackChillsHotFlashesInLast24HoursName]                                 NVARCHAR (200) NULL,
    [AnxietyAttackChillsHotFlashesInLast24HoursValue]                                INT            NULL,
    [AnxietyAttackChillsHotFlashesInLast24HoursIsDefault]                            BIT            NULL,
    [AnxietyAttackChillsHotFlashesInLast24HoursSortOrder]                            INT            NULL,
    [AnxietyAttackChillsHotFlashesInLastMonthCode]                                   NVARCHAR (200) NULL,
    [AnxietyAttackChillsHotFlashesInLastMonthName]                                   NVARCHAR (200) NULL,
    [AnxietyAttackChillsHotFlashesInLastMonthValue]                                  INT            NULL,
    [AnxietyAttackChillsHotFlashesInLastMonthIsDefault]                              BIT            NULL,
    [AnxietyAttackChillsHotFlashesInLastMonthSortOrder]                              INT            NULL,
    [AnxietyAttackChillsHotFlashesInLifetimeCode]                                    NVARCHAR (200) NULL,
    [AnxietyAttackChillsHotFlashesInLifetimeName]                                    NVARCHAR (200) NULL,
    [AnxietyAttackChillsHotFlashesInLifetimeValue]                                   INT            NULL,
    [AnxietyAttackChillsHotFlashesInLifetimeIsDefault]                               BIT            NULL,
    [AnxietyAttackChillsHotFlashesInLifetimeSortOrder]                               INT            NULL,
    [AnxietyAttackChillsHotFlashesRelatedToSubstanceUseCode]                         NVARCHAR (200) NULL,
    [AnxietyAttackChillsHotFlashesRelatedToSubstanceUseName]                         NVARCHAR (200) NULL,
    [AnxietyAttackChillsHotFlashesRelatedToSubstanceUseValue]                        INT            NULL,
    [AnxietyAttackChillsHotFlashesRelatedToSubstanceUseIsDefault]                    BIT            NULL,
    [AnxietyAttackChillsHotFlashesRelatedToSubstanceUseSortOrder]                    INT            NULL,
    [AnxietyAttackChokingInLast24HoursCode]                                          NVARCHAR (200) NULL,
    [AnxietyAttackChokingInLast24HoursName]                                          NVARCHAR (200) NULL,
    [AnxietyAttackChokingInLast24HoursValue]                                         INT            NULL,
    [AnxietyAttackChokingInLast24HoursIsDefault]                                     BIT            NULL,
    [AnxietyAttackChokingInLast24HoursSortOrder]                                     INT            NULL,
    [AnxietyAttackChokingInLastMonthCode]                                            NVARCHAR (200) NULL,
    [AnxietyAttackChokingInLastMonthName]                                            NVARCHAR (200) NULL,
    [AnxietyAttackChokingInLastMonthValue]                                           INT            NULL,
    [AnxietyAttackChokingInLastMonthIsDefault]                                       BIT            NULL,
    [AnxietyAttackChokingInLastMonthSortOrder]                                       INT            NULL,
    [AnxietyAttackChokingInLifetimeCode]                                             NVARCHAR (200) NULL,
    [AnxietyAttackChokingInLifetimeName]                                             NVARCHAR (200) NULL,
    [AnxietyAttackChokingInLifetimeValue]                                            INT            NULL,
    [AnxietyAttackChokingInLifetimeIsDefault]                                        BIT            NULL,
    [AnxietyAttackChokingInLifetimeSortOrder]                                        INT            NULL,
    [AnxietyAttackChokingRelatedToSubstanceUseCode]                                  NVARCHAR (200) NULL,
    [AnxietyAttackChokingRelatedToSubstanceUseName]                                  NVARCHAR (200) NULL,
    [AnxietyAttackChokingRelatedToSubstanceUseValue]                                 INT            NULL,
    [AnxietyAttackChokingRelatedToSubstanceUseIsDefault]                             BIT            NULL,
    [AnxietyAttackChokingRelatedToSubstanceUseSortOrder]                             INT            NULL,
    [AnxietyAttackDistortedRealityInLast24HoursCode]                                 NVARCHAR (200) NULL,
    [AnxietyAttackDistortedRealityInLast24HoursName]                                 NVARCHAR (200) NULL,
    [AnxietyAttackDistortedRealityInLast24HoursValue]                                INT            NULL,
    [AnxietyAttackDistortedRealityInLast24HoursIsDefault]                            BIT            NULL,
    [AnxietyAttackDistortedRealityInLast24HoursSortOrder]                            INT            NULL,
    [AnxietyAttackDistortedRealityInLastMonthCode]                                   NVARCHAR (200) NULL,
    [AnxietyAttackDistortedRealityInLastMonthName]                                   NVARCHAR (200) NULL,
    [AnxietyAttackDistortedRealityInLastMonthValue]                                  INT            NULL,
    [AnxietyAttackDistortedRealityInLastMonthIsDefault]                              BIT            NULL,
    [AnxietyAttackDistortedRealityInLastMonthSortOrder]                              INT            NULL,
    [AnxietyAttackDistortedRealityInLifetimeCode]                                    NVARCHAR (200) NULL,
    [AnxietyAttackDistortedRealityInLifetimeName]                                    NVARCHAR (200) NULL,
    [AnxietyAttackDistortedRealityInLifetimeValue]                                   INT            NULL,
    [AnxietyAttackDistortedRealityInLifetimeIsDefault]                               BIT            NULL,
    [AnxietyAttackDistortedRealityInLifetimeSortOrder]                               INT            NULL,
    [AnxietyAttackDistortedRealityRelatedToSubstanceUseCode]                         NVARCHAR (200) NULL,
    [AnxietyAttackDistortedRealityRelatedToSubstanceUseName]                         NVARCHAR (200) NULL,
    [AnxietyAttackDistortedRealityRelatedToSubstanceUseValue]                        INT            NULL,
    [AnxietyAttackDistortedRealityRelatedToSubstanceUseIsDefault]                    BIT            NULL,
    [AnxietyAttackDistortedRealityRelatedToSubstanceUseSortOrder]                    INT            NULL,
    [AnxietyAttackDizzinessFaintnessInLast24HoursCode]                               NVARCHAR (200) NULL,
    [AnxietyAttackDizzinessFaintnessInLast24HoursName]                               NVARCHAR (200) NULL,
    [AnxietyAttackDizzinessFaintnessInLast24HoursValue]                              INT            NULL,
    [AnxietyAttackDizzinessFaintnessInLast24HoursIsDefault]                          BIT            NULL,
    [AnxietyAttackDizzinessFaintnessInLast24HoursSortOrder]                          INT            NULL,
    [AnxietyAttackDizzinessFaintnessInLastMonthCode]                                 NVARCHAR (200) NULL,
    [AnxietyAttackDizzinessFaintnessInLastMonthName]                                 NVARCHAR (200) NULL,
    [AnxietyAttackDizzinessFaintnessInLastMonthValue]                                INT            NULL,
    [AnxietyAttackDizzinessFaintnessInLastMonthIsDefault]                            BIT            NULL,
    [AnxietyAttackDizzinessFaintnessInLastMonthSortOrder]                            INT            NULL,
    [AnxietyAttackDizzinessFaintnessInLifetimeCode]                                  NVARCHAR (200) NULL,
    [AnxietyAttackDizzinessFaintnessInLifetimeName]                                  NVARCHAR (200) NULL,
    [AnxietyAttackDizzinessFaintnessInLifetimeValue]                                 INT            NULL,
    [AnxietyAttackDizzinessFaintnessInLifetimeIsDefault]                             BIT            NULL,
    [AnxietyAttackDizzinessFaintnessInLifetimeSortOrder]                             INT            NULL,
    [AnxietyAttackDizzinessFaintnessRelatedToSubstanceUseCode]                       NVARCHAR (200) NULL,
    [AnxietyAttackDizzinessFaintnessRelatedToSubstanceUseName]                       NVARCHAR (200) NULL,
    [AnxietyAttackDizzinessFaintnessRelatedToSubstanceUseValue]                      INT            NULL,
    [AnxietyAttackDizzinessFaintnessRelatedToSubstanceUseIsDefault]                  BIT            NULL,
    [AnxietyAttackDizzinessFaintnessRelatedToSubstanceUseSortOrder]                  INT            NULL,
    [AnxietyAttackDyingSensationInLast24HoursCode]                                   NVARCHAR (200) NULL,
    [AnxietyAttackDyingSensationInLast24HoursName]                                   NVARCHAR (200) NULL,
    [AnxietyAttackDyingSensationInLast24HoursValue]                                  INT            NULL,
    [AnxietyAttackDyingSensationInLast24HoursIsDefault]                              BIT            NULL,
    [AnxietyAttackDyingSensationInLast24HoursSortOrder]                              INT            NULL,
    [AnxietyAttackDyingSensationInLastMonthCode]                                     NVARCHAR (200) NULL,
    [AnxietyAttackDyingSensationInLastMonthName]                                     NVARCHAR (200) NULL,
    [AnxietyAttackDyingSensationInLastMonthValue]                                    INT            NULL,
    [AnxietyAttackDyingSensationInLastMonthIsDefault]                                BIT            NULL,
    [AnxietyAttackDyingSensationInLastMonthSortOrder]                                INT            NULL,
    [AnxietyAttackDyingSensationInLifetimeCode]                                      NVARCHAR (200) NULL,
    [AnxietyAttackDyingSensationInLifetimeName]                                      NVARCHAR (200) NULL,
    [AnxietyAttackDyingSensationInLifetimeValue]                                     INT            NULL,
    [AnxietyAttackDyingSensationInLifetimeIsDefault]                                 BIT            NULL,
    [AnxietyAttackDyingSensationInLifetimeSortOrder]                                 INT            NULL,
    [AnxietyAttackDyingSensationRelatedToSubstanceUseCode]                           NVARCHAR (200) NULL,
    [AnxietyAttackDyingSensationRelatedToSubstanceUseName]                           NVARCHAR (200) NULL,
    [AnxietyAttackDyingSensationRelatedToSubstanceUseValue]                          INT            NULL,
    [AnxietyAttackDyingSensationRelatedToSubstanceUseIsDefault]                      BIT            NULL,
    [AnxietyAttackDyingSensationRelatedToSubstanceUseSortOrder]                      INT            NULL,
    [AnxietyAttackInLast24HoursCode]                                                 NVARCHAR (200) NULL,
    [AnxietyAttackInLast24HoursName]                                                 NVARCHAR (200) NULL,
    [AnxietyAttackInLast24HoursValue]                                                INT            NULL,
    [AnxietyAttackInLast24HoursIsDefault]                                            BIT            NULL,
    [AnxietyAttackInLast24HoursSortOrder]                                            INT            NULL,
    [AnxietyAttackInLastMonthCode]                                                   NVARCHAR (200) NULL,
    [AnxietyAttackInLastMonthName]                                                   NVARCHAR (200) NULL,
    [AnxietyAttackInLastMonthValue]                                                  INT            NULL,
    [AnxietyAttackInLastMonthIsDefault]                                              BIT            NULL,
    [AnxietyAttackInLastMonthSortOrder]                                              INT            NULL,
    [AnxietyAttackInLifetimeCode]                                                    NVARCHAR (200) NULL,
    [AnxietyAttackInLifetimeName]                                                    NVARCHAR (200) NULL,
    [AnxietyAttackInLifetimeValue]                                                   INT            NULL,
    [AnxietyAttackInLifetimeIsDefault]                                               BIT            NULL,
    [AnxietyAttackInLifetimeSortOrder]                                               INT            NULL,
    [AnxietyAttackLoseControlInLast24HoursCode]                                      NVARCHAR (200) NULL,
    [AnxietyAttackLoseControlInLast24HoursName]                                      NVARCHAR (200) NULL,
    [AnxietyAttackLoseControlInLast24HoursValue]                                     INT            NULL,
    [AnxietyAttackLoseControlInLast24HoursIsDefault]                                 BIT            NULL,
    [AnxietyAttackLoseControlInLast24HoursSortOrder]                                 INT            NULL,
    [AnxietyAttackLoseControlInLastMonthCode]                                        NVARCHAR (200) NULL,
    [AnxietyAttackLoseControlInLastMonthName]                                        NVARCHAR (200) NULL,
    [AnxietyAttackLoseControlInLastMonthValue]                                       INT            NULL,
    [AnxietyAttackLoseControlInLastMonthIsDefault]                                   BIT            NULL,
    [AnxietyAttackLoseControlInLastMonthSortOrder]                                   INT            NULL,
    [AnxietyAttackLoseControlInLifetimeCode]                                         NVARCHAR (200) NULL,
    [AnxietyAttackLoseControlInLifetimeName]                                         NVARCHAR (200) NULL,
    [AnxietyAttackLoseControlInLifetimeValue]                                        INT            NULL,
    [AnxietyAttackLoseControlInLifetimeIsDefault]                                    BIT            NULL,
    [AnxietyAttackLoseControlInLifetimeSortOrder]                                    INT            NULL,
    [AnxietyAttackLoseControlRelatedToSubstanceUseCode]                              NVARCHAR (200) NULL,
    [AnxietyAttackLoseControlRelatedToSubstanceUseName]                              NVARCHAR (200) NULL,
    [AnxietyAttackLoseControlRelatedToSubstanceUseValue]                             INT            NULL,
    [AnxietyAttackLoseControlRelatedToSubstanceUseIsDefault]                         BIT            NULL,
    [AnxietyAttackLoseControlRelatedToSubstanceUseSortOrder]                         INT            NULL,
    [AnxietyAttackMoreThanOnceInLast24HoursCode]                                     NVARCHAR (200) NULL,
    [AnxietyAttackMoreThanOnceInLast24HoursName]                                     NVARCHAR (200) NULL,
    [AnxietyAttackMoreThanOnceInLast24HoursValue]                                    INT            NULL,
    [AnxietyAttackMoreThanOnceInLast24HoursIsDefault]                                BIT            NULL,
    [AnxietyAttackMoreThanOnceInLast24HoursSortOrder]                                INT            NULL,
    [AnxietyAttackMoreThanOnceInLastMonthCode]                                       NVARCHAR (200) NULL,
    [AnxietyAttackMoreThanOnceInLastMonthName]                                       NVARCHAR (200) NULL,
    [AnxietyAttackMoreThanOnceInLastMonthValue]                                      INT            NULL,
    [AnxietyAttackMoreThanOnceInLastMonthIsDefault]                                  BIT            NULL,
    [AnxietyAttackMoreThanOnceInLastMonthSortOrder]                                  INT            NULL,
    [AnxietyAttackMoreThanOnceInLifetimeCode]                                        NVARCHAR (200) NULL,
    [AnxietyAttackMoreThanOnceInLifetimeName]                                        NVARCHAR (200) NULL,
    [AnxietyAttackMoreThanOnceInLifetimeValue]                                       INT            NULL,
    [AnxietyAttackMoreThanOnceInLifetimeIsDefault]                                   BIT            NULL,
    [AnxietyAttackMoreThanOnceInLifetimeSortOrder]                                   INT            NULL,
    [AnxietyAttackMoreThanOnceRelatedToSubstanceUseCode]                             NVARCHAR (200) NULL,
    [AnxietyAttackMoreThanOnceRelatedToSubstanceUseName]                             NVARCHAR (200) NULL,
    [AnxietyAttackMoreThanOnceRelatedToSubstanceUseValue]                            INT            NULL,
    [AnxietyAttackMoreThanOnceRelatedToSubstanceUseIsDefault]                        BIT            NULL,
    [AnxietyAttackMoreThanOnceRelatedToSubstanceUseSortOrder]                        INT            NULL,
    [AnxietyAttackNauseaDiarrheaInLast24HoursCode]                                   NVARCHAR (200) NULL,
    [AnxietyAttackNauseaDiarrheaInLast24HoursName]                                   NVARCHAR (200) NULL,
    [AnxietyAttackNauseaDiarrheaInLast24HoursValue]                                  INT            NULL,
    [AnxietyAttackNauseaDiarrheaInLast24HoursIsDefault]                              BIT            NULL,
    [AnxietyAttackNauseaDiarrheaInLast24HoursSortOrder]                              INT            NULL,
    [AnxietyAttackNauseaDiarrheaInLastMonthCode]                                     NVARCHAR (200) NULL,
    [AnxietyAttackNauseaDiarrheaInLastMonthName]                                     NVARCHAR (200) NULL,
    [AnxietyAttackNauseaDiarrheaInLastMonthValue]                                    INT            NULL,
    [AnxietyAttackNauseaDiarrheaInLastMonthIsDefault]                                BIT            NULL,
    [AnxietyAttackNauseaDiarrheaInLastMonthSortOrder]                                INT            NULL,
    [AnxietyAttackNauseaDiarrheaInLifetimeCode]                                      NVARCHAR (200) NULL,
    [AnxietyAttackNauseaDiarrheaInLifetimeName]                                      NVARCHAR (200) NULL,
    [AnxietyAttackNauseaDiarrheaInLifetimeValue]                                     INT            NULL,
    [AnxietyAttackNauseaDiarrheaInLifetimeIsDefault]                                 BIT            NULL,
    [AnxietyAttackNauseaDiarrheaInLifetimeSortOrder]                                 INT            NULL,
    [AnxietyAttackNauseaDiarrheaRelatedToSubstanceUseCode]                           NVARCHAR (200) NULL,
    [AnxietyAttackNauseaDiarrheaRelatedToSubstanceUseName]                           NVARCHAR (200) NULL,
    [AnxietyAttackNauseaDiarrheaRelatedToSubstanceUseValue]                          INT            NULL,
    [AnxietyAttackNauseaDiarrheaRelatedToSubstanceUseIsDefault]                      BIT            NULL,
    [AnxietyAttackNauseaDiarrheaRelatedToSubstanceUseSortOrder]                      INT            NULL,
    [AnxietyAttackNumbnessInLast24HoursCode]                                         NVARCHAR (200) NULL,
    [AnxietyAttackNumbnessInLast24HoursName]                                         NVARCHAR (200) NULL,
    [AnxietyAttackNumbnessInLast24HoursValue]                                        INT            NULL,
    [AnxietyAttackNumbnessInLast24HoursIsDefault]                                    BIT            NULL,
    [AnxietyAttackNumbnessInLast24HoursSortOrder]                                    INT            NULL,
    [AnxietyAttackNumbnessInLastMonthCode]                                           NVARCHAR (200) NULL,
    [AnxietyAttackNumbnessInLastMonthName]                                           NVARCHAR (200) NULL,
    [AnxietyAttackNumbnessInLastMonthValue]                                          INT            NULL,
    [AnxietyAttackNumbnessInLastMonthIsDefault]                                      BIT            NULL,
    [AnxietyAttackNumbnessInLastMonthSortOrder]                                      INT            NULL,
    [AnxietyAttackNumbnessInLifetimeCode]                                            NVARCHAR (200) NULL,
    [AnxietyAttackNumbnessInLifetimeName]                                            NVARCHAR (200) NULL,
    [AnxietyAttackNumbnessInLifetimeValue]                                           INT            NULL,
    [AnxietyAttackNumbnessInLifetimeIsDefault]                                       BIT            NULL,
    [AnxietyAttackNumbnessInLifetimeSortOrder]                                       INT            NULL,
    [AnxietyAttackNumbnessRelatedToSubstanceUseCode]                                 NVARCHAR (200) NULL,
    [AnxietyAttackNumbnessRelatedToSubstanceUseName]                                 NVARCHAR (200) NULL,
    [AnxietyAttackNumbnessRelatedToSubstanceUseValue]                                INT            NULL,
    [AnxietyAttackNumbnessRelatedToSubstanceUseIsDefault]                            BIT            NULL,
    [AnxietyAttackNumbnessRelatedToSubstanceUseSortOrder]                            INT            NULL,
    [AnxietyAttackPalpitationsInLast24HoursCode]                                     NVARCHAR (200) NULL,
    [AnxietyAttackPalpitationsInLast24HoursName]                                     NVARCHAR (200) NULL,
    [AnxietyAttackPalpitationsInLast24HoursValue]                                    INT            NULL,
    [AnxietyAttackPalpitationsInLast24HoursIsDefault]                                BIT            NULL,
    [AnxietyAttackPalpitationsInLast24HoursSortOrder]                                INT            NULL,
    [AnxietyAttackPalpitationsInLastMonthCode]                                       NVARCHAR (200) NULL,
    [AnxietyAttackPalpitationsInLastMonthName]                                       NVARCHAR (200) NULL,
    [AnxietyAttackPalpitationsInLastMonthValue]                                      INT            NULL,
    [AnxietyAttackPalpitationsInLastMonthIsDefault]                                  BIT            NULL,
    [AnxietyAttackPalpitationsInLastMonthSortOrder]                                  INT            NULL,
    [AnxietyAttackPalpitationsInLifetimeCode]                                        NVARCHAR (200) NULL,
    [AnxietyAttackPalpitationsInLifetimeName]                                        NVARCHAR (200) NULL,
    [AnxietyAttackPalpitationsInLifetimeValue]                                       INT            NULL,
    [AnxietyAttackPalpitationsInLifetimeIsDefault]                                   BIT            NULL,
    [AnxietyAttackPalpitationsInLifetimeSortOrder]                                   INT            NULL,
    [AnxietyAttackPalpitationsRelatedToSubstanceUseCode]                             NVARCHAR (200) NULL,
    [AnxietyAttackPalpitationsRelatedToSubstanceUseName]                             NVARCHAR (200) NULL,
    [AnxietyAttackPalpitationsRelatedToSubstanceUseValue]                            INT            NULL,
    [AnxietyAttackPalpitationsRelatedToSubstanceUseIsDefault]                        BIT            NULL,
    [AnxietyAttackPalpitationsRelatedToSubstanceUseSortOrder]                        INT            NULL,
    [AnxietyAttackRandomInLast24HoursCode]                                           NVARCHAR (200) NULL,
    [AnxietyAttackRandomInLast24HoursName]                                           NVARCHAR (200) NULL,
    [AnxietyAttackRandomInLast24HoursValue]                                          INT            NULL,
    [AnxietyAttackRandomInLast24HoursIsDefault]                                      BIT            NULL,
    [AnxietyAttackRandomInLast24HoursSortOrder]                                      INT            NULL,
    [AnxietyAttackRandomInLastMonthCode]                                             NVARCHAR (200) NULL,
    [AnxietyAttackRandomInLastMonthName]                                             NVARCHAR (200) NULL,
    [AnxietyAttackRandomInLastMonthValue]                                            INT            NULL,
    [AnxietyAttackRandomInLastMonthIsDefault]                                        BIT            NULL,
    [AnxietyAttackRandomInLastMonthSortOrder]                                        INT            NULL,
    [AnxietyAttackRandomInLifetimeCode]                                              NVARCHAR (200) NULL,
    [AnxietyAttackRandomInLifetimeName]                                              NVARCHAR (200) NULL,
    [AnxietyAttackRandomInLifetimeValue]                                             INT            NULL,
    [AnxietyAttackRandomInLifetimeIsDefault]                                         BIT            NULL,
    [AnxietyAttackRandomInLifetimeSortOrder]                                         INT            NULL,
    [AnxietyAttackRandomRelatedToSubstanceUseCode]                                   NVARCHAR (200) NULL,
    [AnxietyAttackRandomRelatedToSubstanceUseName]                                   NVARCHAR (200) NULL,
    [AnxietyAttackRandomRelatedToSubstanceUseValue]                                  INT            NULL,
    [AnxietyAttackRandomRelatedToSubstanceUseIsDefault]                              BIT            NULL,
    [AnxietyAttackRandomRelatedToSubstanceUseSortOrder]                              INT            NULL,
    [AnxietyAttackShortnessBreathInLast24HoursCode]                                  NVARCHAR (200) NULL,
    [AnxietyAttackShortnessBreathInLast24HoursName]                                  NVARCHAR (200) NULL,
    [AnxietyAttackShortnessBreathInLast24HoursValue]                                 INT            NULL,
    [AnxietyAttackShortnessBreathInLast24HoursIsDefault]                             BIT            NULL,
    [AnxietyAttackShortnessBreathInLast24HoursSortOrder]                             INT            NULL,
    [AnxietyAttackShortnessBreathInLastMonthCode]                                    NVARCHAR (200) NULL,
    [AnxietyAttackShortnessBreathInLastMonthName]                                    NVARCHAR (200) NULL,
    [AnxietyAttackShortnessBreathInLastMonthValue]                                   INT            NULL,
    [AnxietyAttackShortnessBreathInLastMonthIsDefault]                               BIT            NULL,
    [AnxietyAttackShortnessBreathInLastMonthSortOrder]                               INT            NULL,
    [AnxietyAttackShortnessBreathInLifetimeCode]                                     NVARCHAR (200) NULL,
    [AnxietyAttackShortnessBreathInLifetimeName]                                     NVARCHAR (200) NULL,
    [AnxietyAttackShortnessBreathInLifetimeValue]                                    INT            NULL,
    [AnxietyAttackShortnessBreathInLifetimeIsDefault]                                BIT            NULL,
    [AnxietyAttackShortnessBreathInLifetimeSortOrder]                                INT            NULL,
    [AnxietyAttackShortnessBreathRelatedToSubstanceUseCode]                          NVARCHAR (200) NULL,
    [AnxietyAttackShortnessBreathRelatedToSubstanceUseName]                          NVARCHAR (200) NULL,
    [AnxietyAttackShortnessBreathRelatedToSubstanceUseValue]                         INT            NULL,
    [AnxietyAttackShortnessBreathRelatedToSubstanceUseIsDefault]                     BIT            NULL,
    [AnxietyAttackShortnessBreathRelatedToSubstanceUseSortOrder]                     INT            NULL,
    [AnxietyAttackSweatyInLast24HoursCode]                                           NVARCHAR (200) NULL,
    [AnxietyAttackSweatyInLast24HoursName]                                           NVARCHAR (200) NULL,
    [AnxietyAttackSweatyInLast24HoursValue]                                          INT            NULL,
    [AnxietyAttackSweatyInLast24HoursIsDefault]                                      BIT            NULL,
    [AnxietyAttackSweatyInLast24HoursSortOrder]                                      INT            NULL,
    [AnxietyAttackSweatyInLastMonthCode]                                             NVARCHAR (200) NULL,
    [AnxietyAttackSweatyInLastMonthName]                                             NVARCHAR (200) NULL,
    [AnxietyAttackSweatyInLastMonthValue]                                            INT            NULL,
    [AnxietyAttackSweatyInLastMonthIsDefault]                                        BIT            NULL,
    [AnxietyAttackSweatyInLastMonthSortOrder]                                        INT            NULL,
    [AnxietyAttackSweatyInLifetimeCode]                                              NVARCHAR (200) NULL,
    [AnxietyAttackSweatyInLifetimeName]                                              NVARCHAR (200) NULL,
    [AnxietyAttackSweatyInLifetimeValue]                                             INT            NULL,
    [AnxietyAttackSweatyInLifetimeIsDefault]                                         BIT            NULL,
    [AnxietyAttackSweatyInLifetimeSortOrder]                                         INT            NULL,
    [AnxietyAttackSweatyRelatedToSubstanceUseCode]                                   NVARCHAR (200) NULL,
    [AnxietyAttackSweatyRelatedToSubstanceUseName]                                   NVARCHAR (200) NULL,
    [AnxietyAttackSweatyRelatedToSubstanceUseValue]                                  INT            NULL,
    [AnxietyAttackSweatyRelatedToSubstanceUseIsDefault]                              BIT            NULL,
    [AnxietyAttackSweatyRelatedToSubstanceUseSortOrder]                              INT            NULL,
    [AnxietyAttackTremblingInLast24HoursCode]                                        NVARCHAR (200) NULL,
    [AnxietyAttackTremblingInLast24HoursName]                                        NVARCHAR (200) NULL,
    [AnxietyAttackTremblingInLast24HoursValue]                                       INT            NULL,
    [AnxietyAttackTremblingInLast24HoursIsDefault]                                   BIT            NULL,
    [AnxietyAttackTremblingInLast24HoursSortOrder]                                   INT            NULL,
    [AnxietyAttackTremblingInLastMonthCode]                                          NVARCHAR (200) NULL,
    [AnxietyAttackTremblingInLastMonthName]                                          NVARCHAR (200) NULL,
    [AnxietyAttackTremblingInLastMonthValue]                                         INT            NULL,
    [AnxietyAttackTremblingInLastMonthIsDefault]                                     BIT            NULL,
    [AnxietyAttackTremblingInLastMonthSortOrder]                                     INT            NULL,
    [AnxietyAttackTremblingInLifetimeCode]                                           NVARCHAR (200) NULL,
    [AnxietyAttackTremblingInLifetimeName]                                           NVARCHAR (200) NULL,
    [AnxietyAttackTremblingInLifetimeValue]                                          INT            NULL,
    [AnxietyAttackTremblingInLifetimeIsDefault]                                      BIT            NULL,
    [AnxietyAttackTremblingInLifetimeSortOrder]                                      INT            NULL,
    [AnxietyAttackTremblingRelatedToSubstanceUseCode]                                NVARCHAR (200) NULL,
    [AnxietyAttackTremblingRelatedToSubstanceUseName]                                NVARCHAR (200) NULL,
    [AnxietyAttackTremblingRelatedToSubstanceUseValue]                               INT            NULL,
    [AnxietyAttackTremblingRelatedToSubstanceUseIsDefault]                           BIT            NULL,
    [AnxietyAttackTremblingRelatedToSubstanceUseSortOrder]                           INT            NULL,
    [AnxietyAttackWithin24HoursRelatedToSubstanceUseCode]                            NVARCHAR (200) NULL,
    [AnxietyAttackWithin24HoursRelatedToSubstanceUseName]                            NVARCHAR (200) NULL,
    [AnxietyAttackWithin24HoursRelatedToSubstanceUseValue]                           INT            NULL,
    [AnxietyAttackWithin24HoursRelatedToSubstanceUseIsDefault]                       BIT            NULL,
    [AnxietyAttackWithin24HoursRelatedToSubstanceUseSortOrder]                       INT            NULL,
    [AnxietyTensionWorryInLast24HoursCode]                                           NVARCHAR (200) NULL,
    [AnxietyTensionWorryInLast24HoursName]                                           NVARCHAR (200) NULL,
    [AnxietyTensionWorryInLast24HoursValue]                                          INT            NULL,
    [AnxietyTensionWorryInLast24HoursIsDefault]                                      BIT            NULL,
    [AnxietyTensionWorryInLast24HoursSortOrder]                                      INT            NULL,
    [AnxietyTensionWorryInLastMonthCode]                                             NVARCHAR (200) NULL,
    [AnxietyTensionWorryInLastMonthName]                                             NVARCHAR (200) NULL,
    [AnxietyTensionWorryInLastMonthValue]                                            INT            NULL,
    [AnxietyTensionWorryInLastMonthIsDefault]                                        BIT            NULL,
    [AnxietyTensionWorryInLastMonthSortOrder]                                        INT            NULL,
    [AnxietyTensionWorryInLifetimeCode]                                              NVARCHAR (200) NULL,
    [AnxietyTensionWorryInLifetimeName]                                              NVARCHAR (200) NULL,
    [AnxietyTensionWorryInLifetimeValue]                                             INT            NULL,
    [AnxietyTensionWorryInLifetimeIsDefault]                                         BIT            NULL,
    [AnxietyTensionWorryInLifetimeSortOrder]                                         INT            NULL,
    [AnxietyTensionWorryWithin24HoursRelatedToSubstanceUseCode]                      NVARCHAR (200) NULL,
    [AnxietyTensionWorryWithin24HoursRelatedToSubstanceUseName]                      NVARCHAR (200) NULL,
    [AnxietyTensionWorryWithin24HoursRelatedToSubstanceUseValue]                     INT            NULL,
    [AnxietyTensionWorryWithin24HoursRelatedToSubstanceUseIsDefault]                 BIT            NULL,
    [AnxietyTensionWorryWithin24HoursRelatedToSubstanceUseSortOrder]                 INT            NULL,
    [DepressionWithin24HoursRelatedToSubstanceUseCode]                               NVARCHAR (200) NULL,
    [DepressionWithin24HoursRelatedToSubstanceUseName]                               NVARCHAR (200) NULL,
    [DepressionWithin24HoursRelatedToSubstanceUseValue]                              INT            NULL,
    [DepressionWithin24HoursRelatedToSubstanceUseIsDefault]                          BIT            NULL,
    [DepressionWithin24HoursRelatedToSubstanceUseSortOrder]                          INT            NULL,
    [EmotionalProblemsCorrelationWithSubstanceUseCode]                               NVARCHAR (200) NULL,
    [EmotionalProblemsCorrelationWithSubstanceUseName]                               NVARCHAR (200) NULL,
    [EmotionalProblemsCorrelationWithSubstanceUseValue]                              INT            NULL,
    [EmotionalProblemsCorrelationWithSubstanceUseIsDefault]                          BIT            NULL,
    [EmotionalProblemsCorrelationWithSubstanceUseSortOrder]                          INT            NULL,
    [FeelLikeFailureInLast24HoursCode]                                               NVARCHAR (200) NULL,
    [FeelLikeFailureInLast24HoursName]                                               NVARCHAR (200) NULL,
    [FeelLikeFailureInLast24HoursValue]                                              INT            NULL,
    [FeelLikeFailureInLast24HoursIsDefault]                                          BIT            NULL,
    [FeelLikeFailureInLast24HoursSortOrder]                                          INT            NULL,
    [FeelLikeFailureInLast24HoursRelatedToSubstanceUseCode]                          NVARCHAR (200) NULL,
    [FeelLikeFailureInLast24HoursRelatedToSubstanceUseName]                          NVARCHAR (200) NULL,
    [FeelLikeFailureInLast24HoursRelatedToSubstanceUseValue]                         INT            NULL,
    [FeelLikeFailureInLast24HoursRelatedToSubstanceUseIsDefault]                     BIT            NULL,
    [FeelLikeFailureInLast24HoursRelatedToSubstanceUseSortOrder]                     INT            NULL,
    [FeelLikeFailureInLastMonthCode]                                                 NVARCHAR (200) NULL,
    [FeelLikeFailureInLastMonthName]                                                 NVARCHAR (200) NULL,
    [FeelLikeFailureInLastMonthValue]                                                INT            NULL,
    [FeelLikeFailureInLastMonthIsDefault]                                            BIT            NULL,
    [FeelLikeFailureInLastMonthSortOrder]                                            INT            NULL,
    [FeelLikeFailureInLifetimeCode]                                                  NVARCHAR (200) NULL,
    [FeelLikeFailureInLifetimeName]                                                  NVARCHAR (200) NULL,
    [FeelLikeFailureInLifetimeValue]                                                 INT            NULL,
    [FeelLikeFailureInLifetimeIsDefault]                                             BIT            NULL,
    [FeelLikeFailureInLifetimeSortOrder]                                             INT            NULL,
    [HowDifficultProblemsForWorkHomeAndSocialInteractionCode]                        NVARCHAR (200) NULL,
    [HowDifficultProblemsForWorkHomeAndSocialInteractionName]                        NVARCHAR (200) NULL,
    [HowDifficultProblemsForWorkHomeAndSocialInteractionValue]                       INT            NULL,
    [HowDifficultProblemsForWorkHomeAndSocialInteractionIsDefault]                   BIT            NULL,
    [HowDifficultProblemsForWorkHomeAndSocialInteractionSortOrder]                   INT            NULL,
    [HowDifficultToSelfManageEmotionalProblemsCode]                                  NVARCHAR (200) NULL,
    [HowDifficultToSelfManageEmotionalProblemsName]                                  NVARCHAR (200) NULL,
    [HowDifficultToSelfManageEmotionalProblemsValue]                                 INT            NULL,
    [HowDifficultToSelfManageEmotionalProblemsIsDefault]                             BIT            NULL,
    [HowDifficultToSelfManageEmotionalProblemsSortOrder]                             INT            NULL,
    [HowEmotionalProblemsImpactRecoveryEffortsCode]                                  NVARCHAR (200) NULL,
    [HowEmotionalProblemsImpactRecoveryEffortsName]                                  NVARCHAR (200) NULL,
    [HowEmotionalProblemsImpactRecoveryEffortsValue]                                 INT            NULL,
    [HowEmotionalProblemsImpactRecoveryEffortsIsDefault]                             BIT            NULL,
    [HowEmotionalProblemsImpactRecoveryEffortsSortOrder]                             INT            NULL,
    [HowImportantPsychologicalEmotionalCounselingCode]                               NVARCHAR (200) NULL,
    [HowImportantPsychologicalEmotionalCounselingName]                               NVARCHAR (200) NULL,
    [HowImportantPsychologicalEmotionalCounselingValue]                              INT            NULL,
    [HowImportantPsychologicalEmotionalCounselingIsDefault]                          BIT            NULL,
    [HowImportantPsychologicalEmotionalCounselingSortOrder]                          INT            NULL,
    [HowTroubledByPsychologicalEmotionalProblemsLast30DaysCode]                      NVARCHAR (200) NULL,
    [HowTroubledByPsychologicalEmotionalProblemsLast30DaysName]                      NVARCHAR (200) NULL,
    [HowTroubledByPsychologicalEmotionalProblemsLast30DaysValue]                     INT            NULL,
    [HowTroubledByPsychologicalEmotionalProblemsLast30DaysIsDefault]                 BIT            NULL,
    [HowTroubledByPsychologicalEmotionalProblemsLast30DaysSortOrder]                 INT            NULL,
    [InabilityToFeelPleasureFromActivitiesInLast24HoursCode]                         NVARCHAR (200) NULL,
    [InabilityToFeelPleasureFromActivitiesInLast24HoursName]                         NVARCHAR (200) NULL,
    [InabilityToFeelPleasureFromActivitiesInLast24HoursValue]                        INT            NULL,
    [InabilityToFeelPleasureFromActivitiesInLast24HoursIsDefault]                    BIT            NULL,
    [InabilityToFeelPleasureFromActivitiesInLast24HoursSortOrder]                    INT            NULL,
    [InabilityToFeelPleasureFromActivitiesInLastMonthCode]                           NVARCHAR (200) NULL,
    [InabilityToFeelPleasureFromActivitiesInLastMonthName]                           NVARCHAR (200) NULL,
    [InabilityToFeelPleasureFromActivitiesInLastMonthValue]                          INT            NULL,
    [InabilityToFeelPleasureFromActivitiesInLastMonthIsDefault]                      BIT            NULL,
    [InabilityToFeelPleasureFromActivitiesInLastMonthSortOrder]                      INT            NULL,
    [InabilityToFeelPleasureFromActivitiesInLifetimeCode]                            NVARCHAR (200) NULL,
    [InabilityToFeelPleasureFromActivitiesInLifetimeName]                            NVARCHAR (200) NULL,
    [InabilityToFeelPleasureFromActivitiesInLifetimeValue]                           INT            NULL,
    [InabilityToFeelPleasureFromActivitiesInLifetimeIsDefault]                       BIT            NULL,
    [InabilityToFeelPleasureFromActivitiesInLifetimeSortOrder]                       INT            NULL,
    [InabilityToFeelPleasureFromActivitiesRelatedToSubstanceUseCode]                 NVARCHAR (200) NULL,
    [InabilityToFeelPleasureFromActivitiesRelatedToSubstanceUseName]                 NVARCHAR (200) NULL,
    [InabilityToFeelPleasureFromActivitiesRelatedToSubstanceUseValue]                INT            NULL,
    [InabilityToFeelPleasureFromActivitiesRelatedToSubstanceUseIsDefault]            BIT            NULL,
    [InabilityToFeelPleasureFromActivitiesRelatedToSubstanceUseSortOrder]            INT            NULL,
    [IsReceivingNeededCareCode]                                                      NVARCHAR (200) NULL,
    [IsReceivingNeededCareName]                                                      NVARCHAR (200) NULL,
    [IsReceivingNeededCareValue]                                                     INT            NULL,
    [IsReceivingNeededCareIsDefault]                                                 BIT            NULL,
    [IsReceivingNeededCareSortOrder]                                                 INT            NULL,
    [MovingSpeakingSlowlyInLast24HoursCode]                                          NVARCHAR (200) NULL,
    [MovingSpeakingSlowlyInLast24HoursName]                                          NVARCHAR (200) NULL,
    [MovingSpeakingSlowlyInLast24HoursValue]                                         INT            NULL,
    [MovingSpeakingSlowlyInLast24HoursIsDefault]                                     BIT            NULL,
    [MovingSpeakingSlowlyInLast24HoursSortOrder]                                     INT            NULL,
    [MovingSpeakingSlowlyInLastMonthCode]                                            NVARCHAR (200) NULL,
    [MovingSpeakingSlowlyInLastMonthName]                                            NVARCHAR (200) NULL,
    [MovingSpeakingSlowlyInLastMonthValue]                                           INT            NULL,
    [MovingSpeakingSlowlyInLastMonthIsDefault]                                       BIT            NULL,
    [MovingSpeakingSlowlyInLastMonthSortOrder]                                       INT            NULL,
    [MovingSpeakingSlowlyInLifetimeCode]                                             NVARCHAR (200) NULL,
    [MovingSpeakingSlowlyInLifetimeName]                                             NVARCHAR (200) NULL,
    [MovingSpeakingSlowlyInLifetimeValue]                                            INT            NULL,
    [MovingSpeakingSlowlyInLifetimeIsDefault]                                        BIT            NULL,
    [MovingSpeakingSlowlyInLifetimeSortOrder]                                        INT            NULL,
    [MovingSpeakingSlowlyWithin24HoursRelatedToSubstanceUseCode]                     NVARCHAR (200) NULL,
    [MovingSpeakingSlowlyWithin24HoursRelatedToSubstanceUseName]                     NVARCHAR (200) NULL,
    [MovingSpeakingSlowlyWithin24HoursRelatedToSubstanceUseValue]                    INT            NULL,
    [MovingSpeakingSlowlyWithin24HoursRelatedToSubstanceUseIsDefault]                BIT            NULL,
    [MovingSpeakingSlowlyWithin24HoursRelatedToSubstanceUseSortOrder]                INT            NULL,
    [PoorAppetiteOrOvereatingInLast24HoursCode]                                      NVARCHAR (200) NULL,
    [PoorAppetiteOrOvereatingInLast24HoursName]                                      NVARCHAR (200) NULL,
    [PoorAppetiteOrOvereatingInLast24HoursValue]                                     INT            NULL,
    [PoorAppetiteOrOvereatingInLast24HoursIsDefault]                                 BIT            NULL,
    [PoorAppetiteOrOvereatingInLast24HoursSortOrder]                                 INT            NULL,
    [PoorAppetiteOrOvereatingInLast24HoursRelatedToSubstanceUseCode]                 NVARCHAR (200) NULL,
    [PoorAppetiteOrOvereatingInLast24HoursRelatedToSubstanceUseName]                 NVARCHAR (200) NULL,
    [PoorAppetiteOrOvereatingInLast24HoursRelatedToSubstanceUseValue]                INT            NULL,
    [PoorAppetiteOrOvereatingInLast24HoursRelatedToSubstanceUseIsDefault]            BIT            NULL,
    [PoorAppetiteOrOvereatingInLast24HoursRelatedToSubstanceUseSortOrder]            INT            NULL,
    [PoorAppetiteOrOvereatingInLastMonthCode]                                        NVARCHAR (200) NULL,
    [PoorAppetiteOrOvereatingInLastMonthName]                                        NVARCHAR (200) NULL,
    [PoorAppetiteOrOvereatingInLastMonthValue]                                       INT            NULL,
    [PoorAppetiteOrOvereatingInLastMonthIsDefault]                                   BIT            NULL,
    [PoorAppetiteOrOvereatingInLastMonthSortOrder]                                   INT            NULL,
    [PoorAppetiteOrOvereatingInLifetimeCode]                                         NVARCHAR (200) NULL,
    [PoorAppetiteOrOvereatingInLifetimeName]                                         NVARCHAR (200) NULL,
    [PoorAppetiteOrOvereatingInLifetimeValue]                                        INT            NULL,
    [PoorAppetiteOrOvereatingInLifetimeIsDefault]                                    BIT            NULL,
    [PoorAppetiteOrOvereatingInLifetimeSortOrder]                                    INT            NULL,
    [SignificantPeriodAttemptedSuicideInLast24HoursCode]                             NVARCHAR (200) NULL,
    [SignificantPeriodAttemptedSuicideInLast24HoursName]                             NVARCHAR (200) NULL,
    [SignificantPeriodAttemptedSuicideInLast24HoursValue]                            INT            NULL,
    [SignificantPeriodAttemptedSuicideInLast24HoursIsDefault]                        BIT            NULL,
    [SignificantPeriodAttemptedSuicideInLast24HoursSortOrder]                        INT            NULL,
    [SignificantPeriodAttemptedSuicideInLastMonthCode]                               NVARCHAR (200) NULL,
    [SignificantPeriodAttemptedSuicideInLastMonthName]                               NVARCHAR (200) NULL,
    [SignificantPeriodAttemptedSuicideInLastMonthValue]                              INT            NULL,
    [SignificantPeriodAttemptedSuicideInLastMonthIsDefault]                          BIT            NULL,
    [SignificantPeriodAttemptedSuicideInLastMonthSortOrder]                          INT            NULL,
    [SignificantPeriodAttemptedSuicideInLifetimeCode]                                NVARCHAR (200) NULL,
    [SignificantPeriodAttemptedSuicideInLifetimeName]                                NVARCHAR (200) NULL,
    [SignificantPeriodAttemptedSuicideInLifetimeValue]                               INT            NULL,
    [SignificantPeriodAttemptedSuicideInLifetimeIsDefault]                           BIT            NULL,
    [SignificantPeriodAttemptedSuicideInLifetimeSortOrder]                           INT            NULL,
    [SignificantPeriodAttemptedSuicideRelatedToSubstanceUseCode]                     NVARCHAR (200) NULL,
    [SignificantPeriodAttemptedSuicideRelatedToSubstanceUseName]                     NVARCHAR (200) NULL,
    [SignificantPeriodAttemptedSuicideRelatedToSubstanceUseValue]                    INT            NULL,
    [SignificantPeriodAttemptedSuicideRelatedToSubstanceUseIsDefault]                BIT            NULL,
    [SignificantPeriodAttemptedSuicideRelatedToSubstanceUseSortOrder]                INT            NULL,
    [SignificantPeriodCurbingViolentBehaviorInLast24HoursCode]                       NVARCHAR (200) NULL,
    [SignificantPeriodCurbingViolentBehaviorInLast24HoursName]                       NVARCHAR (200) NULL,
    [SignificantPeriodCurbingViolentBehaviorInLast24HoursValue]                      INT            NULL,
    [SignificantPeriodCurbingViolentBehaviorInLast24HoursIsDefault]                  BIT            NULL,
    [SignificantPeriodCurbingViolentBehaviorInLast24HoursSortOrder]                  INT            NULL,
    [SignificantPeriodCurbingViolentBehaviorInLastMonthCode]                         NVARCHAR (200) NULL,
    [SignificantPeriodCurbingViolentBehaviorInLastMonthName]                         NVARCHAR (200) NULL,
    [SignificantPeriodCurbingViolentBehaviorInLastMonthValue]                        INT            NULL,
    [SignificantPeriodCurbingViolentBehaviorInLastMonthIsDefault]                    BIT            NULL,
    [SignificantPeriodCurbingViolentBehaviorInLastMonthSortOrder]                    INT            NULL,
    [SignificantPeriodCurbingViolentBehaviorInLifetimeCode]                          NVARCHAR (200) NULL,
    [SignificantPeriodCurbingViolentBehaviorInLifetimeName]                          NVARCHAR (200) NULL,
    [SignificantPeriodCurbingViolentBehaviorInLifetimeValue]                         INT            NULL,
    [SignificantPeriodCurbingViolentBehaviorInLifetimeIsDefault]                     BIT            NULL,
    [SignificantPeriodCurbingViolentBehaviorInLifetimeSortOrder]                     INT            NULL,
    [SignificantPeriodCurbingViolentBehaviorRelatedToSubstanceUseCode]               NVARCHAR (200) NULL,
    [SignificantPeriodCurbingViolentBehaviorRelatedToSubstanceUseName]               NVARCHAR (200) NULL,
    [SignificantPeriodCurbingViolentBehaviorRelatedToSubstanceUseValue]              INT            NULL,
    [SignificantPeriodCurbingViolentBehaviorRelatedToSubstanceUseIsDefault]          BIT            NULL,
    [SignificantPeriodCurbingViolentBehaviorRelatedToSubstanceUseSortOrder]          INT            NULL,
    [SignificantPeriodExcessiveBehaviorInLast24HoursCode]                            NVARCHAR (200) NULL,
    [SignificantPeriodExcessiveBehaviorInLast24HoursName]                            NVARCHAR (200) NULL,
    [SignificantPeriodExcessiveBehaviorInLast24HoursValue]                           INT            NULL,
    [SignificantPeriodExcessiveBehaviorInLast24HoursIsDefault]                       BIT            NULL,
    [SignificantPeriodExcessiveBehaviorInLast24HoursSortOrder]                       INT            NULL,
    [SignificantPeriodExcessiveBehaviorInLastMonthCode]                              NVARCHAR (200) NULL,
    [SignificantPeriodExcessiveBehaviorInLastMonthName]                              NVARCHAR (200) NULL,
    [SignificantPeriodExcessiveBehaviorInLastMonthValue]                             INT            NULL,
    [SignificantPeriodExcessiveBehaviorInLastMonthIsDefault]                         BIT            NULL,
    [SignificantPeriodExcessiveBehaviorInLastMonthSortOrder]                         INT            NULL,
    [SignificantPeriodExcessiveBehaviorInLifetimeCode]                               NVARCHAR (200) NULL,
    [SignificantPeriodExcessiveBehaviorInLifetimeName]                               NVARCHAR (200) NULL,
    [SignificantPeriodExcessiveBehaviorInLifetimeValue]                              INT            NULL,
    [SignificantPeriodExcessiveBehaviorInLifetimeIsDefault]                          BIT            NULL,
    [SignificantPeriodExcessiveBehaviorInLifetimeSortOrder]                          INT            NULL,
    [SignificantPeriodExcessiveBehaviorRelatedToSubstanceUseCode]                    NVARCHAR (200) NULL,
    [SignificantPeriodExcessiveBehaviorRelatedToSubstanceUseName]                    NVARCHAR (200) NULL,
    [SignificantPeriodExcessiveBehaviorRelatedToSubstanceUseValue]                   INT            NULL,
    [SignificantPeriodExcessiveBehaviorRelatedToSubstanceUseIsDefault]               BIT            NULL,
    [SignificantPeriodExcessiveBehaviorRelatedToSubstanceUseSortOrder]               INT            NULL,
    [SignificantPeriodFidgetingInLast24HoursCode]                                    NVARCHAR (200) NULL,
    [SignificantPeriodFidgetingInLast24HoursName]                                    NVARCHAR (200) NULL,
    [SignificantPeriodFidgetingInLast24HoursValue]                                   INT            NULL,
    [SignificantPeriodFidgetingInLast24HoursIsDefault]                               BIT            NULL,
    [SignificantPeriodFidgetingInLast24HoursSortOrder]                               INT            NULL,
    [SignificantPeriodFidgetingInLastMonthCode]                                      NVARCHAR (200) NULL,
    [SignificantPeriodFidgetingInLastMonthName]                                      NVARCHAR (200) NULL,
    [SignificantPeriodFidgetingInLastMonthValue]                                     INT            NULL,
    [SignificantPeriodFidgetingInLastMonthIsDefault]                                 BIT            NULL,
    [SignificantPeriodFidgetingInLastMonthSortOrder]                                 INT            NULL,
    [SignificantPeriodFidgetingInLifetimeCode]                                       NVARCHAR (200) NULL,
    [SignificantPeriodFidgetingInLifetimeName]                                       NVARCHAR (200) NULL,
    [SignificantPeriodFidgetingInLifetimeValue]                                      INT            NULL,
    [SignificantPeriodFidgetingInLifetimeIsDefault]                                  BIT            NULL,
    [SignificantPeriodFidgetingInLifetimeSortOrder]                                  INT            NULL,
    [SignificantPeriodFidgetingRelatedToSubstanceUseCode]                            NVARCHAR (200) NULL,
    [SignificantPeriodFidgetingRelatedToSubstanceUseName]                            NVARCHAR (200) NULL,
    [SignificantPeriodFidgetingRelatedToSubstanceUseValue]                           INT            NULL,
    [SignificantPeriodFidgetingRelatedToSubstanceUseIsDefault]                       BIT            NULL,
    [SignificantPeriodFidgetingRelatedToSubstanceUseSortOrder]                       INT            NULL,
    [SignificantPeriodFlashbacksInLast24HoursCode]                                   NVARCHAR (200) NULL,
    [SignificantPeriodFlashbacksInLast24HoursName]                                   NVARCHAR (200) NULL,
    [SignificantPeriodFlashbacksInLast24HoursValue]                                  INT            NULL,
    [SignificantPeriodFlashbacksInLast24HoursIsDefault]                              BIT            NULL,
    [SignificantPeriodFlashbacksInLast24HoursSortOrder]                              INT            NULL,
    [SignificantPeriodFlashbacksInLastMonthCode]                                     NVARCHAR (200) NULL,
    [SignificantPeriodFlashbacksInLastMonthName]                                     NVARCHAR (200) NULL,
    [SignificantPeriodFlashbacksInLastMonthValue]                                    INT            NULL,
    [SignificantPeriodFlashbacksInLastMonthIsDefault]                                BIT            NULL,
    [SignificantPeriodFlashbacksInLastMonthSortOrder]                                INT            NULL,
    [SignificantPeriodFlashbacksInLifetimeCode]                                      NVARCHAR (200) NULL,
    [SignificantPeriodFlashbacksInLifetimeName]                                      NVARCHAR (200) NULL,
    [SignificantPeriodFlashbacksInLifetimeValue]                                     INT            NULL,
    [SignificantPeriodFlashbacksInLifetimeIsDefault]                                 BIT            NULL,
    [SignificantPeriodFlashbacksInLifetimeSortOrder]                                 INT            NULL,
    [SignificantPeriodFlashbacksRelatedToSubstanceUseCode]                           NVARCHAR (200) NULL,
    [SignificantPeriodFlashbacksRelatedToSubstanceUseName]                           NVARCHAR (200) NULL,
    [SignificantPeriodFlashbacksRelatedToSubstanceUseValue]                          INT            NULL,
    [SignificantPeriodFlashbacksRelatedToSubstanceUseIsDefault]                      BIT            NULL,
    [SignificantPeriodFlashbacksRelatedToSubstanceUseSortOrder]                      INT            NULL,
    [SignificantPeriodHallucinationsInLast24HoursCode]                               NVARCHAR (200) NULL,
    [SignificantPeriodHallucinationsInLast24HoursName]                               NVARCHAR (200) NULL,
    [SignificantPeriodHallucinationsInLast24HoursValue]                              INT            NULL,
    [SignificantPeriodHallucinationsInLast24HoursIsDefault]                          BIT            NULL,
    [SignificantPeriodHallucinationsInLast24HoursSortOrder]                          INT            NULL,
    [SignificantPeriodHallucinationsInLastMonthCode]                                 NVARCHAR (200) NULL,
    [SignificantPeriodHallucinationsInLastMonthName]                                 NVARCHAR (200) NULL,
    [SignificantPeriodHallucinationsInLastMonthValue]                                INT            NULL,
    [SignificantPeriodHallucinationsInLastMonthIsDefault]                            BIT            NULL,
    [SignificantPeriodHallucinationsInLastMonthSortOrder]                            INT            NULL,
    [SignificantPeriodHallucinationsInLifetimeCode]                                  NVARCHAR (200) NULL,
    [SignificantPeriodHallucinationsInLifetimeName]                                  NVARCHAR (200) NULL,
    [SignificantPeriodHallucinationsInLifetimeValue]                                 INT            NULL,
    [SignificantPeriodHallucinationsInLifetimeIsDefault]                             BIT            NULL,
    [SignificantPeriodHallucinationsInLifetimeSortOrder]                             INT            NULL,
    [SignificantPeriodHallucinationsRelatedToSubstanceUseCode]                       NVARCHAR (200) NULL,
    [SignificantPeriodHallucinationsRelatedToSubstanceUseName]                       NVARCHAR (200) NULL,
    [SignificantPeriodHallucinationsRelatedToSubstanceUseValue]                      INT            NULL,
    [SignificantPeriodHallucinationsRelatedToSubstanceUseIsDefault]                  BIT            NULL,
    [SignificantPeriodHallucinationsRelatedToSubstanceUseSortOrder]                  INT            NULL,
    [SignificantPeriodImpairedThoughtInLast24HoursCode]                              NVARCHAR (200) NULL,
    [SignificantPeriodImpairedThoughtInLast24HoursName]                              NVARCHAR (200) NULL,
    [SignificantPeriodImpairedThoughtInLast24HoursValue]                             INT            NULL,
    [SignificantPeriodImpairedThoughtInLast24HoursIsDefault]                         BIT            NULL,
    [SignificantPeriodImpairedThoughtInLast24HoursSortOrder]                         INT            NULL,
    [SignificantPeriodImpairedThoughtInLastMonthCode]                                NVARCHAR (200) NULL,
    [SignificantPeriodImpairedThoughtInLastMonthName]                                NVARCHAR (200) NULL,
    [SignificantPeriodImpairedThoughtInLastMonthValue]                               INT            NULL,
    [SignificantPeriodImpairedThoughtInLastMonthIsDefault]                           BIT            NULL,
    [SignificantPeriodImpairedThoughtInLastMonthSortOrder]                           INT            NULL,
    [SignificantPeriodImpairedThoughtInLifetimeCode]                                 NVARCHAR (200) NULL,
    [SignificantPeriodImpairedThoughtInLifetimeName]                                 NVARCHAR (200) NULL,
    [SignificantPeriodImpairedThoughtInLifetimeValue]                                INT            NULL,
    [SignificantPeriodImpairedThoughtInLifetimeIsDefault]                            BIT            NULL,
    [SignificantPeriodImpairedThoughtInLifetimeSortOrder]                            INT            NULL,
    [SignificantPeriodImpairedThoughtRelatedToSubstanceUseCode]                      NVARCHAR (200) NULL,
    [SignificantPeriodImpairedThoughtRelatedToSubstanceUseName]                      NVARCHAR (200) NULL,
    [SignificantPeriodImpairedThoughtRelatedToSubstanceUseValue]                     INT            NULL,
    [SignificantPeriodImpairedThoughtRelatedToSubstanceUseIsDefault]                 BIT            NULL,
    [SignificantPeriodImpairedThoughtRelatedToSubstanceUseSortOrder]                 INT            NULL,
    [SignificantPeriodIrritabilityInLast24HoursCode]                                 NVARCHAR (200) NULL,
    [SignificantPeriodIrritabilityInLast24HoursName]                                 NVARCHAR (200) NULL,
    [SignificantPeriodIrritabilityInLast24HoursValue]                                INT            NULL,
    [SignificantPeriodIrritabilityInLast24HoursIsDefault]                            BIT            NULL,
    [SignificantPeriodIrritabilityInLast24HoursSortOrder]                            INT            NULL,
    [SignificantPeriodIrritabilityInLastMonthCode]                                   NVARCHAR (200) NULL,
    [SignificantPeriodIrritabilityInLastMonthName]                                   NVARCHAR (200) NULL,
    [SignificantPeriodIrritabilityInLastMonthValue]                                  INT            NULL,
    [SignificantPeriodIrritabilityInLastMonthIsDefault]                              BIT            NULL,
    [SignificantPeriodIrritabilityInLastMonthSortOrder]                              INT            NULL,
    [SignificantPeriodIrritabilityInLifetimeCode]                                    NVARCHAR (200) NULL,
    [SignificantPeriodIrritabilityInLifetimeName]                                    NVARCHAR (200) NULL,
    [SignificantPeriodIrritabilityInLifetimeValue]                                   INT            NULL,
    [SignificantPeriodIrritabilityInLifetimeIsDefault]                               BIT            NULL,
    [SignificantPeriodIrritabilityInLifetimeSortOrder]                               INT            NULL,
    [SignificantPeriodIrritabilityRelatedToSubstanceUseCode]                         NVARCHAR (200) NULL,
    [SignificantPeriodIrritabilityRelatedToSubstanceUseName]                         NVARCHAR (200) NULL,
    [SignificantPeriodIrritabilityRelatedToSubstanceUseValue]                        INT            NULL,
    [SignificantPeriodIrritabilityRelatedToSubstanceUseIsDefault]                    BIT            NULL,
    [SignificantPeriodIrritabilityRelatedToSubstanceUseSortOrder]                    INT            NULL,
    [SignificantPeriodLethargyInLast24HoursCode]                                     NVARCHAR (200) NULL,
    [SignificantPeriodLethargyInLast24HoursName]                                     NVARCHAR (200) NULL,
    [SignificantPeriodLethargyInLast24HoursValue]                                    INT            NULL,
    [SignificantPeriodLethargyInLast24HoursIsDefault]                                BIT            NULL,
    [SignificantPeriodLethargyInLast24HoursSortOrder]                                INT            NULL,
    [SignificantPeriodLethargyInLastMonthCode]                                       NVARCHAR (200) NULL,
    [SignificantPeriodLethargyInLastMonthName]                                       NVARCHAR (200) NULL,
    [SignificantPeriodLethargyInLastMonthValue]                                      INT            NULL,
    [SignificantPeriodLethargyInLastMonthIsDefault]                                  BIT            NULL,
    [SignificantPeriodLethargyInLastMonthSortOrder]                                  INT            NULL,
    [SignificantPeriodLethargyInLifetimeCode]                                        NVARCHAR (200) NULL,
    [SignificantPeriodLethargyInLifetimeName]                                        NVARCHAR (200) NULL,
    [SignificantPeriodLethargyInLifetimeValue]                                       INT            NULL,
    [SignificantPeriodLethargyInLifetimeIsDefault]                                   BIT            NULL,
    [SignificantPeriodLethargyInLifetimeSortOrder]                                   INT            NULL,
    [SignificantPeriodLethargyRelatedToSubstanceUseCode]                             NVARCHAR (200) NULL,
    [SignificantPeriodLethargyRelatedToSubstanceUseName]                             NVARCHAR (200) NULL,
    [SignificantPeriodLethargyRelatedToSubstanceUseValue]                            INT            NULL,
    [SignificantPeriodLethargyRelatedToSubstanceUseIsDefault]                        BIT            NULL,
    [SignificantPeriodLethargyRelatedToSubstanceUseSortOrder]                        INT            NULL,
    [SignificantPeriodMuscleTensionInLast24HoursCode]                                NVARCHAR (200) NULL,
    [SignificantPeriodMuscleTensionInLast24HoursName]                                NVARCHAR (200) NULL,
    [SignificantPeriodMuscleTensionInLast24HoursValue]                               INT            NULL,
    [SignificantPeriodMuscleTensionInLast24HoursIsDefault]                           BIT            NULL,
    [SignificantPeriodMuscleTensionInLast24HoursSortOrder]                           INT            NULL,
    [SignificantPeriodMuscleTensionInLastMonthCode]                                  NVARCHAR (200) NULL,
    [SignificantPeriodMuscleTensionInLastMonthName]                                  NVARCHAR (200) NULL,
    [SignificantPeriodMuscleTensionInLastMonthValue]                                 INT            NULL,
    [SignificantPeriodMuscleTensionInLastMonthIsDefault]                             BIT            NULL,
    [SignificantPeriodMuscleTensionInLastMonthSortOrder]                             INT            NULL,
    [SignificantPeriodMuscleTensionInLifetimeCode]                                   NVARCHAR (200) NULL,
    [SignificantPeriodMuscleTensionInLifetimeName]                                   NVARCHAR (200) NULL,
    [SignificantPeriodMuscleTensionInLifetimeValue]                                  INT            NULL,
    [SignificantPeriodMuscleTensionInLifetimeIsDefault]                              BIT            NULL,
    [SignificantPeriodMuscleTensionInLifetimeSortOrder]                              INT            NULL,
    [SignificantPeriodMuscleTensionRelatedToSubstanceUseCode]                        NVARCHAR (200) NULL,
    [SignificantPeriodMuscleTensionRelatedToSubstanceUseName]                        NVARCHAR (200) NULL,
    [SignificantPeriodMuscleTensionRelatedToSubstanceUseValue]                       INT            NULL,
    [SignificantPeriodMuscleTensionRelatedToSubstanceUseIsDefault]                   BIT            NULL,
    [SignificantPeriodMuscleTensionRelatedToSubstanceUseSortOrder]                   INT            NULL,
    [SignificantPeriodNegativeThoughtsInLast24HoursCode]                             NVARCHAR (200) NULL,
    [SignificantPeriodNegativeThoughtsInLast24HoursName]                             NVARCHAR (200) NULL,
    [SignificantPeriodNegativeThoughtsInLast24HoursValue]                            INT            NULL,
    [SignificantPeriodNegativeThoughtsInLast24HoursIsDefault]                        BIT            NULL,
    [SignificantPeriodNegativeThoughtsInLast24HoursSortOrder]                        INT            NULL,
    [SignificantPeriodNegativeThoughtsInLastMonthCode]                               NVARCHAR (200) NULL,
    [SignificantPeriodNegativeThoughtsInLastMonthName]                               NVARCHAR (200) NULL,
    [SignificantPeriodNegativeThoughtsInLastMonthValue]                              INT            NULL,
    [SignificantPeriodNegativeThoughtsInLastMonthIsDefault]                          BIT            NULL,
    [SignificantPeriodNegativeThoughtsInLastMonthSortOrder]                          INT            NULL,
    [SignificantPeriodNegativeThoughtsInLifetimeCode]                                NVARCHAR (200) NULL,
    [SignificantPeriodNegativeThoughtsInLifetimeName]                                NVARCHAR (200) NULL,
    [SignificantPeriodNegativeThoughtsInLifetimeValue]                               INT            NULL,
    [SignificantPeriodNegativeThoughtsInLifetimeIsDefault]                           BIT            NULL,
    [SignificantPeriodNegativeThoughtsInLifetimeSortOrder]                           INT            NULL,
    [SignificantPeriodNegativeThoughtsRelatedToSubstanceUseCode]                     NVARCHAR (200) NULL,
    [SignificantPeriodNegativeThoughtsRelatedToSubstanceUseName]                     NVARCHAR (200) NULL,
    [SignificantPeriodNegativeThoughtsRelatedToSubstanceUseValue]                    INT            NULL,
    [SignificantPeriodNegativeThoughtsRelatedToSubstanceUseIsDefault]                BIT            NULL,
    [SignificantPeriodNegativeThoughtsRelatedToSubstanceUseSortOrder]                INT            NULL,
    [SignificantPeriodOfSeriousDepressionInLast24HoursCode]                          NVARCHAR (200) NULL,
    [SignificantPeriodOfSeriousDepressionInLast24HoursName]                          NVARCHAR (200) NULL,
    [SignificantPeriodOfSeriousDepressionInLast24HoursValue]                         INT            NULL,
    [SignificantPeriodOfSeriousDepressionInLast24HoursIsDefault]                     BIT            NULL,
    [SignificantPeriodOfSeriousDepressionInLast24HoursSortOrder]                     INT            NULL,
    [SignificantPeriodOfSeriousDepressionInLastMonthCode]                            NVARCHAR (200) NULL,
    [SignificantPeriodOfSeriousDepressionInLastMonthName]                            NVARCHAR (200) NULL,
    [SignificantPeriodOfSeriousDepressionInLastMonthValue]                           INT            NULL,
    [SignificantPeriodOfSeriousDepressionInLastMonthIsDefault]                       BIT            NULL,
    [SignificantPeriodOfSeriousDepressionInLastMonthSortOrder]                       INT            NULL,
    [SignificantPeriodOfSeriousDepressionInLifetimeCode]                             NVARCHAR (200) NULL,
    [SignificantPeriodOfSeriousDepressionInLifetimeName]                             NVARCHAR (200) NULL,
    [SignificantPeriodOfSeriousDepressionInLifetimeValue]                            INT            NULL,
    [SignificantPeriodOfSeriousDepressionInLifetimeIsDefault]                        BIT            NULL,
    [SignificantPeriodOfSeriousDepressionInLifetimeSortOrder]                        INT            NULL,
    [SignificantPeriodParanoiaInLast24HoursCode]                                     NVARCHAR (200) NULL,
    [SignificantPeriodParanoiaInLast24HoursName]                                     NVARCHAR (200) NULL,
    [SignificantPeriodParanoiaInLast24HoursValue]                                    INT            NULL,
    [SignificantPeriodParanoiaInLast24HoursIsDefault]                                BIT            NULL,
    [SignificantPeriodParanoiaInLast24HoursSortOrder]                                INT            NULL,
    [SignificantPeriodParanoiaInLastMonthCode]                                       NVARCHAR (200) NULL,
    [SignificantPeriodParanoiaInLastMonthName]                                       NVARCHAR (200) NULL,
    [SignificantPeriodParanoiaInLastMonthValue]                                      INT            NULL,
    [SignificantPeriodParanoiaInLastMonthIsDefault]                                  BIT            NULL,
    [SignificantPeriodParanoiaInLastMonthSortOrder]                                  INT            NULL,
    [SignificantPeriodParanoiaInLifetimeCode]                                        NVARCHAR (200) NULL,
    [SignificantPeriodParanoiaInLifetimeName]                                        NVARCHAR (200) NULL,
    [SignificantPeriodParanoiaInLifetimeValue]                                       INT            NULL,
    [SignificantPeriodParanoiaInLifetimeIsDefault]                                   BIT            NULL,
    [SignificantPeriodParanoiaInLifetimeSortOrder]                                   INT            NULL,
    [SignificantPeriodParanoiaRelatedToSubstanceUseCode]                             NVARCHAR (200) NULL,
    [SignificantPeriodParanoiaRelatedToSubstanceUseName]                             NVARCHAR (200) NULL,
    [SignificantPeriodParanoiaRelatedToSubstanceUseValue]                            INT            NULL,
    [SignificantPeriodParanoiaRelatedToSubstanceUseIsDefault]                        BIT            NULL,
    [SignificantPeriodParanoiaRelatedToSubstanceUseSortOrder]                        INT            NULL,
    [SignificantPeriodSleepDisorderInLast24HoursCode]                                NVARCHAR (200) NULL,
    [SignificantPeriodSleepDisorderInLast24HoursName]                                NVARCHAR (200) NULL,
    [SignificantPeriodSleepDisorderInLast24HoursValue]                               INT            NULL,
    [SignificantPeriodSleepDisorderInLast24HoursIsDefault]                           BIT            NULL,
    [SignificantPeriodSleepDisorderInLast24HoursSortOrder]                           INT            NULL,
    [SignificantPeriodSleepDisorderInLastMonthCode]                                  NVARCHAR (200) NULL,
    [SignificantPeriodSleepDisorderInLastMonthName]                                  NVARCHAR (200) NULL,
    [SignificantPeriodSleepDisorderInLastMonthValue]                                 INT            NULL,
    [SignificantPeriodSleepDisorderInLastMonthIsDefault]                             BIT            NULL,
    [SignificantPeriodSleepDisorderInLastMonthSortOrder]                             INT            NULL,
    [SignificantPeriodSleepDisorderInLifetimeCode]                                   NVARCHAR (200) NULL,
    [SignificantPeriodSleepDisorderInLifetimeName]                                   NVARCHAR (200) NULL,
    [SignificantPeriodSleepDisorderInLifetimeValue]                                  INT            NULL,
    [SignificantPeriodSleepDisorderInLifetimeIsDefault]                              BIT            NULL,
    [SignificantPeriodSleepDisorderInLifetimeSortOrder]                              INT            NULL,
    [SignificantPeriodSleepDisorderRelatedToSubstanceUseCode]                        NVARCHAR (200) NULL,
    [SignificantPeriodSleepDisorderRelatedToSubstanceUseName]                        NVARCHAR (200) NULL,
    [SignificantPeriodSleepDisorderRelatedToSubstanceUseValue]                       INT            NULL,
    [SignificantPeriodSleepDisorderRelatedToSubstanceUseIsDefault]                   BIT            NULL,
    [SignificantPeriodSleepDisorderRelatedToSubstanceUseSortOrder]                   INT            NULL,
    [SignificantPeriodSuicidalThoughtsInLast24HoursCode]                             NVARCHAR (200) NULL,
    [SignificantPeriodSuicidalThoughtsInLast24HoursName]                             NVARCHAR (200) NULL,
    [SignificantPeriodSuicidalThoughtsInLast24HoursValue]                            INT            NULL,
    [SignificantPeriodSuicidalThoughtsInLast24HoursIsDefault]                        BIT            NULL,
    [SignificantPeriodSuicidalThoughtsInLast24HoursSortOrder]                        INT            NULL,
    [SignificantPeriodSuicidalThoughtsInLastMonthCode]                               NVARCHAR (200) NULL,
    [SignificantPeriodSuicidalThoughtsInLastMonthName]                               NVARCHAR (200) NULL,
    [SignificantPeriodSuicidalThoughtsInLastMonthValue]                              INT            NULL,
    [SignificantPeriodSuicidalThoughtsInLastMonthIsDefault]                          BIT            NULL,
    [SignificantPeriodSuicidalThoughtsInLastMonthSortOrder]                          INT            NULL,
    [SignificantPeriodSuicidalThoughtsInLifetimeCode]                                NVARCHAR (200) NULL,
    [SignificantPeriodSuicidalThoughtsInLifetimeName]                                NVARCHAR (200) NULL,
    [SignificantPeriodSuicidalThoughtsInLifetimeValue]                               INT            NULL,
    [SignificantPeriodSuicidalThoughtsInLifetimeIsDefault]                           BIT            NULL,
    [SignificantPeriodSuicidalThoughtsInLifetimeSortOrder]                           INT            NULL,
    [SignificantPeriodSuicidalThoughtsRelatedToSubstanceUseCode]                     NVARCHAR (200) NULL,
    [SignificantPeriodSuicidalThoughtsRelatedToSubstanceUseName]                     NVARCHAR (200) NULL,
    [SignificantPeriodSuicidalThoughtsRelatedToSubstanceUseValue]                    INT            NULL,
    [SignificantPeriodSuicidalThoughtsRelatedToSubstanceUseIsDefault]                BIT            NULL,
    [SignificantPeriodSuicidalThoughtsRelatedToSubstanceUseSortOrder]                INT            NULL,
    [SignificantPeriodThoughtsOfSelfInjuryInLast24HoursCode]                         NVARCHAR (200) NULL,
    [SignificantPeriodThoughtsOfSelfInjuryInLast24HoursName]                         NVARCHAR (200) NULL,
    [SignificantPeriodThoughtsOfSelfInjuryInLast24HoursValue]                        INT            NULL,
    [SignificantPeriodThoughtsOfSelfInjuryInLast24HoursIsDefault]                    BIT            NULL,
    [SignificantPeriodThoughtsOfSelfInjuryInLast24HoursSortOrder]                    INT            NULL,
    [SignificantPeriodThoughtsOfSelfInjuryInLastMonthCode]                           NVARCHAR (200) NULL,
    [SignificantPeriodThoughtsOfSelfInjuryInLastMonthName]                           NVARCHAR (200) NULL,
    [SignificantPeriodThoughtsOfSelfInjuryInLastMonthValue]                          INT            NULL,
    [SignificantPeriodThoughtsOfSelfInjuryInLastMonthIsDefault]                      BIT            NULL,
    [SignificantPeriodThoughtsOfSelfInjuryInLastMonthSortOrder]                      INT            NULL,
    [SignificantPeriodThoughtsOfSelfInjuryInLifetimeCode]                            NVARCHAR (200) NULL,
    [SignificantPeriodThoughtsOfSelfInjuryInLifetimeName]                            NVARCHAR (200) NULL,
    [SignificantPeriodThoughtsOfSelfInjuryInLifetimeValue]                           INT            NULL,
    [SignificantPeriodThoughtsOfSelfInjuryInLifetimeIsDefault]                       BIT            NULL,
    [SignificantPeriodThoughtsOfSelfInjuryInLifetimeSortOrder]                       INT            NULL,
    [SignificantPeriodThoughtsOfSelfInjuryRelatedToSubstanceUseCode]                 NVARCHAR (200) NULL,
    [SignificantPeriodThoughtsOfSelfInjuryRelatedToSubstanceUseName]                 NVARCHAR (200) NULL,
    [SignificantPeriodThoughtsOfSelfInjuryRelatedToSubstanceUseValue]                INT            NULL,
    [SignificantPeriodThoughtsOfSelfInjuryRelatedToSubstanceUseIsDefault]            BIT            NULL,
    [SignificantPeriodThoughtsOfSelfInjuryRelatedToSubstanceUseSortOrder]            INT            NULL,
    [SignificantPeriodTroubleWithAttitudeTowardOthersInLast24HoursCode]              NVARCHAR (200) NULL,
    [SignificantPeriodTroubleWithAttitudeTowardOthersInLast24HoursName]              NVARCHAR (200) NULL,
    [SignificantPeriodTroubleWithAttitudeTowardOthersInLast24HoursValue]             INT            NULL,
    [SignificantPeriodTroubleWithAttitudeTowardOthersInLast24HoursIsDefault]         BIT            NULL,
    [SignificantPeriodTroubleWithAttitudeTowardOthersInLast24HoursSortOrder]         INT            NULL,
    [SignificantPeriodTroubleWithAttitudeTowardOthersInLastMonthCode]                NVARCHAR (200) NULL,
    [SignificantPeriodTroubleWithAttitudeTowardOthersInLastMonthName]                NVARCHAR (200) NULL,
    [SignificantPeriodTroubleWithAttitudeTowardOthersInLastMonthValue]               INT            NULL,
    [SignificantPeriodTroubleWithAttitudeTowardOthersInLastMonthIsDefault]           BIT            NULL,
    [SignificantPeriodTroubleWithAttitudeTowardOthersInLastMonthSortOrder]           INT            NULL,
    [SignificantPeriodTroubleWithAttitudeTowardOthersInLifetimeCode]                 NVARCHAR (200) NULL,
    [SignificantPeriodTroubleWithAttitudeTowardOthersInLifetimeName]                 NVARCHAR (200) NULL,
    [SignificantPeriodTroubleWithAttitudeTowardOthersInLifetimeValue]                INT            NULL,
    [SignificantPeriodTroubleWithAttitudeTowardOthersInLifetimeIsDefault]            BIT            NULL,
    [SignificantPeriodTroubleWithAttitudeTowardOthersInLifetimeSortOrder]            INT            NULL,
    [SignificantPeriodTroubleWithAttitudeTowardOthersRelatedToSubstanceUseCode]      NVARCHAR (200) NULL,
    [SignificantPeriodTroubleWithAttitudeTowardOthersRelatedToSubstanceUseName]      NVARCHAR (200) NULL,
    [SignificantPeriodTroubleWithAttitudeTowardOthersRelatedToSubstanceUseValue]     INT            NULL,
    [SignificantPeriodTroubleWithAttitudeTowardOthersRelatedToSubstanceUseIsDefault] BIT            NULL,
    [SignificantPeriodTroubleWithAttitudeTowardOthersRelatedToSubstanceUseSortOrder] INT            NULL,
    [SignificantPeriodUntruePerceptionInLast24HoursCode]                             NVARCHAR (200) NULL,
    [SignificantPeriodUntruePerceptionInLast24HoursName]                             NVARCHAR (200) NULL,
    [SignificantPeriodUntruePerceptionInLast24HoursValue]                            INT            NULL,
    [SignificantPeriodUntruePerceptionInLast24HoursIsDefault]                        BIT            NULL,
    [SignificantPeriodUntruePerceptionInLast24HoursSortOrder]                        INT            NULL,
    [SignificantPeriodUntruePerceptionInLastMonthCode]                               NVARCHAR (200) NULL,
    [SignificantPeriodUntruePerceptionInLastMonthName]                               NVARCHAR (200) NULL,
    [SignificantPeriodUntruePerceptionInLastMonthValue]                              INT            NULL,
    [SignificantPeriodUntruePerceptionInLastMonthIsDefault]                          BIT            NULL,
    [SignificantPeriodUntruePerceptionInLastMonthSortOrder]                          INT            NULL,
    [SignificantPeriodUntruePerceptionInLifetimeCode]                                NVARCHAR (200) NULL,
    [SignificantPeriodUntruePerceptionInLifetimeName]                                NVARCHAR (200) NULL,
    [SignificantPeriodUntruePerceptionInLifetimeValue]                               INT            NULL,
    [SignificantPeriodUntruePerceptionInLifetimeIsDefault]                           BIT            NULL,
    [SignificantPeriodUntruePerceptionInLifetimeSortOrder]                           INT            NULL,
    [SignificantPeriodUntruePerceptionRelatedToSubstanceUseCode]                     NVARCHAR (200) NULL,
    [SignificantPeriodUntruePerceptionRelatedToSubstanceUseName]                     NVARCHAR (200) NULL,
    [SignificantPeriodUntruePerceptionRelatedToSubstanceUseValue]                    INT            NULL,
    [SignificantPeriodUntruePerceptionRelatedToSubstanceUseIsDefault]                BIT            NULL,
    [SignificantPeriodUntruePerceptionRelatedToSubstanceUseSortOrder]                INT            NULL,
    [SignificantPeriodViolentUrgesInLast24HoursCode]                                 NVARCHAR (200) NULL,
    [SignificantPeriodViolentUrgesInLast24HoursName]                                 NVARCHAR (200) NULL,
    [SignificantPeriodViolentUrgesInLast24HoursValue]                                INT            NULL,
    [SignificantPeriodViolentUrgesInLast24HoursIsDefault]                            BIT            NULL,
    [SignificantPeriodViolentUrgesInLast24HoursSortOrder]                            INT            NULL,
    [SignificantPeriodViolentUrgesInLastMonthCode]                                   NVARCHAR (200) NULL,
    [SignificantPeriodViolentUrgesInLastMonthName]                                   NVARCHAR (200) NULL,
    [SignificantPeriodViolentUrgesInLastMonthValue]                                  INT            NULL,
    [SignificantPeriodViolentUrgesInLastMonthIsDefault]                              BIT            NULL,
    [SignificantPeriodViolentUrgesInLastMonthSortOrder]                              INT            NULL,
    [SignificantPeriodViolentUrgesInLifetimeCode]                                    NVARCHAR (200) NULL,
    [SignificantPeriodViolentUrgesInLifetimeName]                                    NVARCHAR (200) NULL,
    [SignificantPeriodViolentUrgesInLifetimeValue]                                   INT            NULL,
    [SignificantPeriodViolentUrgesInLifetimeIsDefault]                               BIT            NULL,
    [SignificantPeriodViolentUrgesInLifetimeSortOrder]                               INT            NULL,
    [SignificantPeriodViolentUrgesRelatedToSubstanceUseCode]                         NVARCHAR (200) NULL,
    [SignificantPeriodViolentUrgesRelatedToSubstanceUseName]                         NVARCHAR (200) NULL,
    [SignificantPeriodViolentUrgesRelatedToSubstanceUseValue]                        INT            NULL,
    [SignificantPeriodViolentUrgesRelatedToSubstanceUseIsDefault]                    BIT            NULL,
    [SignificantPeriodViolentUrgesRelatedToSubstanceUseSortOrder]                    INT            NULL,
    [WorriedAboutAnxietyAttackInLast24HoursCode]                                     NVARCHAR (200) NULL,
    [WorriedAboutAnxietyAttackInLast24HoursName]                                     NVARCHAR (200) NULL,
    [WorriedAboutAnxietyAttackInLast24HoursValue]                                    INT            NULL,
    [WorriedAboutAnxietyAttackInLast24HoursIsDefault]                                BIT            NULL,
    [WorriedAboutAnxietyAttackInLast24HoursSortOrder]                                INT            NULL,
    [WorriedAboutAnxietyAttackInLastMonthCode]                                       NVARCHAR (200) NULL,
    [WorriedAboutAnxietyAttackInLastMonthName]                                       NVARCHAR (200) NULL,
    [WorriedAboutAnxietyAttackInLastMonthValue]                                      INT            NULL,
    [WorriedAboutAnxietyAttackInLastMonthIsDefault]                                  BIT            NULL,
    [WorriedAboutAnxietyAttackInLastMonthSortOrder]                                  INT            NULL,
    [WorriedAboutAnxietyAttackInLifetimeCode]                                        NVARCHAR (200) NULL,
    [WorriedAboutAnxietyAttackInLifetimeName]                                        NVARCHAR (200) NULL,
    [WorriedAboutAnxietyAttackInLifetimeValue]                                       INT            NULL,
    [WorriedAboutAnxietyAttackInLifetimeIsDefault]                                   BIT            NULL,
    [WorriedAboutAnxietyAttackInLifetimeSortOrder]                                   INT            NULL,
    [WorriedAboutAnxietyAttackRelatedToSubstanceUseCode]                             NVARCHAR (200) NULL,
    [WorriedAboutAnxietyAttackRelatedToSubstanceUseName]                             NVARCHAR (200) NULL,
    [WorriedAboutAnxietyAttackRelatedToSubstanceUseValue]                            INT            NULL,
    [WorriedAboutAnxietyAttackRelatedToSubstanceUseIsDefault]                        BIT            NULL,
    [WorriedAboutAnxietyAttackRelatedToSubstanceUseSortOrder]                        INT            NULL,
    PRIMARY KEY CLUSTERED ([PsychologicalHistoryKey] ASC)
);




















GO


