CREATE TABLE [AssessmentModule].[ReviewSection] (
    [ReviewSectionKey]                                             BIGINT         NOT NULL,
    [Version]                                                      INT            NOT NULL,
    [ReferredToBiomedicallyEnhancedProgram]                        BIT            NULL,
    [IsVisited]                                                    BIT            NOT NULL,
    [AgreesWithTreatmentReferredToCode]                            NVARCHAR (200) NULL,
    [AgreesWithTreatmentReferredToName]                            NVARCHAR (200) NULL,
    [AgreesWithTreatmentReferredToValue]                           INT            NULL,
    [AgreesWithTreatmentReferredToIsDefault]                       BIT            NULL,
    [AgreesWithTreatmentReferredToSortOrder]                       INT            NULL,
    [CategoryOfFinalDispositionCode]                               NVARCHAR (200) NULL,
    [CategoryOfFinalDispositionName]                               NVARCHAR (200) NULL,
    [CategoryOfFinalDispositionValue]                              INT            NULL,
    [CategoryOfFinalDispositionIsDefault]                          BIT            NULL,
    [CategoryOfFinalDispositionSortOrder]                          INT            NULL,
    [DisagreesWithPpcThinksNeedsDifferentTreatmentRatingCode]      NVARCHAR (200) NULL,
    [DisagreesWithPpcThinksNeedsDifferentTreatmentRatingName]      NVARCHAR (200) NULL,
    [DisagreesWithPpcThinksNeedsDifferentTreatmentRatingValue]     INT            NULL,
    [DisagreesWithPpcThinksNeedsDifferentTreatmentRatingIsDefault] BIT            NULL,
    [DisagreesWithPpcThinksNeedsDifferentTreatmentRatingSortOrder] INT            NULL,
    [HasInterviewerDifferedFromPpcFinalRecommendationCode]         NVARCHAR (200) NULL,
    [HasInterviewerDifferedFromPpcFinalRecommendationName]         NVARCHAR (200) NULL,
    [HasInterviewerDifferedFromPpcFinalRecommendationValue]        INT            NULL,
    [HasInterviewerDifferedFromPpcFinalRecommendationIsDefault]    BIT            NULL,
    [HasInterviewerDifferedFromPpcFinalRecommendationSortOrder]    INT            NULL,
    [IntentionToFollowThroughWithReferralWithin30DaysCode]         NVARCHAR (200) NULL,
    [IntentionToFollowThroughWithReferralWithin30DaysName]         NVARCHAR (200) NULL,
    [IntentionToFollowThroughWithReferralWithin30DaysValue]        INT            NULL,
    [IntentionToFollowThroughWithReferralWithin30DaysIsDefault]    BIT            NULL,
    [IntentionToFollowThroughWithReferralWithin30DaysSortOrder]    INT            NULL,
    [InvolvementOfMaintainingTotalAbstinanceInNinetyDaysCode]      NVARCHAR (200) NULL,
    [InvolvementOfMaintainingTotalAbstinanceInNinetyDaysName]      NVARCHAR (200) NULL,
    [InvolvementOfMaintainingTotalAbstinanceInNinetyDaysValue]     INT            NULL,
    [InvolvementOfMaintainingTotalAbstinanceInNinetyDaysIsDefault] BIT            NULL,
    [InvolvementOfMaintainingTotalAbstinanceInNinetyDaysSortOrder] INT            NULL,
    [MaintainTotalAbstinenceInNinetyDayCode]                       NVARCHAR (200) NULL,
    [MaintainTotalAbstinenceInNinetyDayName]                       NVARCHAR (200) NULL,
    [MaintainTotalAbstinenceInNinetyDayValue]                      INT            NULL,
    [MaintainTotalAbstinenceInNinetyDayIsDefault]                  BIT            NULL,
    [MaintainTotalAbstinenceInNinetyDaySortOrder]                  INT            NULL,
    [MotivationForRecoveryAtThisTimeCode]                          NVARCHAR (200) NULL,
    [MotivationForRecoveryAtThisTimeName]                          NVARCHAR (200) NULL,
    [MotivationForRecoveryAtThisTimeValue]                         INT            NULL,
    [MotivationForRecoveryAtThisTimeIsDefault]                     BIT            NULL,
    [MotivationForRecoveryAtThisTimeSortOrder]                     INT            NULL,
    [ProbabilityOfBeingTreatedInNext90DaysCode]                    NVARCHAR (200) NULL,
    [ProbabilityOfBeingTreatedInNext90DaysName]                    NVARCHAR (200) NULL,
    [ProbabilityOfBeingTreatedInNext90DaysValue]                   INT            NULL,
    [ProbabilityOfBeingTreatedInNext90DaysIsDefault]               BIT            NULL,
    [ProbabilityOfBeingTreatedInNext90DaysSortOrder]               INT            NULL,
    [QualityOfIntakeProcessCode]                                   NVARCHAR (200) NULL,
    [QualityOfIntakeProcessName]                                   NVARCHAR (200) NULL,
    [QualityOfIntakeProcessValue]                                  INT            NULL,
    [QualityOfIntakeProcessIsDefault]                              BIT            NULL,
    [QualityOfIntakeProcessSortOrder]                              INT            NULL,
    [QualityOfServiceReceivedCode]                                 NVARCHAR (200) NULL,
    [QualityOfServiceReceivedName]                                 NVARCHAR (200) NULL,
    [QualityOfServiceReceivedValue]                                INT            NULL,
    [QualityOfServiceReceivedIsDefault]                            BIT            NULL,
    [QualityOfServiceReceivedSortOrder]                            INT            NULL,
    [ReasonForFinalDispositionCode]                                NVARCHAR (200) NULL,
    [ReasonForFinalDispositionName]                                NVARCHAR (200) NULL,
    [ReasonForFinalDispositionValue]                               INT            NULL,
    [ReasonForFinalDispositionIsDefault]                           BIT            NULL,
    [ReasonForFinalDispositionSortOrder]                           INT            NULL,
    [ReferralFollowThroughInNext30DaysCode]                        NVARCHAR (200) NULL,
    [ReferralFollowThroughInNext30DaysName]                        NVARCHAR (200) NULL,
    [ReferralFollowThroughInNext30DaysValue]                       INT            NULL,
    [ReferralFollowThroughInNext30DaysIsDefault]                   BIT            NULL,
    [ReferralFollowThroughInNext30DaysSortOrder]                   INT            NULL,
    [SatificationWithTimeToCompleteInterviewCode]                  NVARCHAR (200) NULL,
    [SatificationWithTimeToCompleteInterviewName]                  NVARCHAR (200) NULL,
    [SatificationWithTimeToCompleteInterviewValue]                 INT            NULL,
    [SatificationWithTimeToCompleteInterviewIsDefault]             BIT            NULL,
    [SatificationWithTimeToCompleteInterviewSortOrder]             INT            NULL,
    [SubCategoryOfFinalDispositionCode]                            NVARCHAR (200) NULL,
    [SubCategoryOfFinalDispositionName]                            NVARCHAR (200) NULL,
    [SubCategoryOfFinalDispositionValue]                           INT            NULL,
    [SubCategoryOfFinalDispositionIsDefault]                       BIT            NULL,
    [SubCategoryOfFinalDispositionSortOrder]                       INT            NULL,
    [WillingnessToRecommendFriendToProgramCode]                    NVARCHAR (200) NULL,
    [WillingnessToRecommendFriendToProgramName]                    NVARCHAR (200) NULL,
    [WillingnessToRecommendFriendToProgramValue]                   INT            NULL,
    [WillingnessToRecommendFriendToProgramIsDefault]               BIT            NULL,
    [WillingnessToRecommendFriendToProgramSortOrder]               INT            NULL,
    PRIMARY KEY CLUSTERED ([ReviewSectionKey] ASC)
);

