//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asam.Ppc.Service.Messages.Assessment {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AsamPpcScaleResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AsamPpcScaleResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Asam.Ppc.Service.Messages.Assessment.AsamPpcScaleResources", typeof(AsamPpcScaleResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No treatment necessary|Treatment needed to intervene in life threatening situation.
        /// </summary>
        public static string AlcoholAndDrugInterviewerRating_InterviewerScoreOfAlcoholTreatmentNeed {
            get {
                return ResourceManager.GetString("AlcoholAndDrugInterviewerRating_InterviewerScoreOfAlcoholTreatmentNeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows appropriate concern w/insight and acceptance of an addiction problem||Is ambivalent, somewhat less concerned than circumstances warrant||Rationalizes addiction problems as mostly due to other causes||Shows no evidence of concern at all||Openly rejects evidence of apparent addiction problems|.
        /// </summary>
        public static string AlcoholAndDrugInterviewerRating_InterviewerScoreOfAttitude {
            get {
                return ResourceManager.GetString("AlcoholAndDrugInterviewerRating_InterviewerScoreOfAttitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No treatment necessary|Treatment needed to intervene in life threatening situation.
        /// </summary>
        public static string AlcoholAndDrugInterviewerRating_InterviewerScoreOfDrugTreatmentNeed {
            get {
                return ResourceManager.GetString("AlcoholAndDrugInterviewerRating_InterviewerScoreOfDrugTreatmentNeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has completed treatment and fully engaged in periodic maintenance efforts|Is actively participating in, or completing treatment with maintenance plans|Is spontaneously seeking treatment||Is open to treatment with prompting||Is ambivalent or unclear of plans||Wants to drop treatment|Refuses any treatment.
        /// </summary>
        public static string AlcoholAndDrugInterviewerRating_InterviewerScoreOfReadiness {
            get {
                return ResourceManager.GetString("AlcoholAndDrugInterviewerRating_InterviewerScoreOfReadiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no nausea and no vomiting|Mild nausea with no vomiting|Constant dry heaves but no vomiting|||Constant nausea, frequent dry heaves and vomiting|| ||.
        /// </summary>
        public static string CinaScale_ExperiencedNauseaOrVomitedRecently {
            get {
                return ResourceManager.GetString("CinaScale_ExperiencedNauseaOrVomitedRecently", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No treatment necessary|Treatment needed to intervene in life threatening situation.
        /// </summary>
        public static string EmploymentAndSupportSection_InterviewerRatingPatientNeedForEmploymentCounseling {
            get {
                return ResourceManager.GetString("EmploymentAndSupportSection_InterviewerRatingPatientNeedForEmploymentCounseling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No treatment necessary|Treatment needed to intervene in life threatening situation.
        /// </summary>
        public static string FamilyAndSocialHistorySection_InterviewerRatingPatientNeedForFamilySocialCounseling {
            get {
                return ResourceManager.GetString("FamilyAndSocialHistorySection_InterviewerRatingPatientNeedForFamilySocialCounseli" +
                        "ng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not at All|Slightly symptomatic (patient reports symptoms, no impairment of behavior or function)||Moderately (observable symptoms, no impairment)||Considerably (overt or persistent symptoms suggesting risk of impairment)||Extremely (persistent symptoms with evidence of or report of impairment)|.
        /// </summary>
        public static string InterviewerRating_AppearanceofAgitation {
            get {
                return ResourceManager.GetString("InterviewerRating_AppearanceofAgitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not at All|Slightly symptomatic (patient reports symptoms, no impairment of behavior or function)||Moderately (observable symptoms, no impairment)||Considerably (overt or persistent symptoms suggesting risk of impairment)||Extremely (persistent symptoms with evidence of or report of impairment)|.
        /// </summary>
        public static string InterviewerRating_AppearanceOfAnxietyNervousness {
            get {
                return ResourceManager.GetString("InterviewerRating_AppearanceOfAnxietyNervousness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not at All|Slightly symptomatic (patient reports symptoms, no impairment of behavior or function)||Moderately (observable symptoms, no impairment)||Considerably (overt or persistent symptoms suggesting risk of impairment)||Extremely (persistent symptoms with evidence of or report of impairment)|.
        /// </summary>
        public static string InterviewerRating_AppearanceOfDepressionWithdrawal {
            get {
                return ResourceManager.GetString("InterviewerRating_AppearanceOfDepressionWithdrawal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not at All|Slightly symptomatic (patient reports symptoms, no impairment of behavior or function)||Moderately (observable symptoms, no impairment)||Considerably (overt or persistent symptoms suggesting risk of impairment)||Extremely (persistent symptoms with evidence of or report of impairment)|.
        /// </summary>
        public static string InterviewerRating_AppearanceOfFluctuatingOrientationInLast24Hours {
            get {
                return ResourceManager.GetString("InterviewerRating_AppearanceOfFluctuatingOrientationInLast24Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not at All|Slightly symptomatic (patient reports symptoms, no impairment of behavior or function)||Moderately (observable symptoms, no impairment)||Considerably (overt or persistent symptoms suggesting risk of impairment)||Extremely (persistent symptoms with evidence of or report of impairment)|.
        /// </summary>
        public static string InterviewerRating_AppearanceOfHostility {
            get {
                return ResourceManager.GetString("InterviewerRating_AppearanceOfHostility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not at All|Slightly symptomatic (patient reports symptoms, no impairment of behavior or function)||Moderately (observable symptoms, no impairment)||Considerably (overt or persistent symptoms suggesting risk of impairment)||Extremely (persistent symptoms with evidence of or report of impairment)|.
        /// </summary>
        public static string InterviewerRating_AppearanceOfLethargy {
            get {
                return ResourceManager.GetString("InterviewerRating_AppearanceOfLethargy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not at All|Slightly symptomatic (patient reports symptoms, no impairment of behavior or function)||Moderately (observable symptoms, no impairment)||Considerably (overt or persistent symptoms suggesting risk of impairment)||Extremely (persistent symptoms with evidence of or report of impairment)|.
        /// </summary>
        public static string InterviewerRating_AppearanceOfParanoiaOrImpairedThinking {
            get {
                return ResourceManager.GetString("InterviewerRating_AppearanceOfParanoiaOrImpairedThinking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not at All|Slightly symptomatic (patient reports symptoms, no impairment of behavior or function)||Moderately (observable symptoms, no impairment)||Considerably (overt or persistent symptoms suggesting risk of impairment)||Extremely (persistent symptoms with evidence of or report of impairment)|.
        /// </summary>
        public static string InterviewerRating_AppearanceOfSpeechImpairmentBadPosture {
            get {
                return ResourceManager.GetString("InterviewerRating_AppearanceOfSpeechImpairmentBadPosture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not at All|Slightly symptomatic (patient reports symptoms, no impairment of behavior or function)||Moderately (observable symptoms, no impairment)||Considerably (overt or persistent symptoms suggesting risk of impairment)||Extremely (persistent symptoms with evidence of or report of impairment)|.
        /// </summary>
        public static string InterviewerRating_AppearanceOfTroubleConcentratingOrRemembering {
            get {
                return ResourceManager.GetString("InterviewerRating_AppearanceOfTroubleConcentratingOrRemembering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not at All|Slightly symptomatic (patient reports symptoms, no impairment of behavior or function)||Moderately (observable symptoms, no impairment)||Considerably (overt or persistent symptoms suggesting risk of impairment)||Extremely (persistent symptoms with evidence of or report of impairment)|.
        /// </summary>
        public static string InterviewerRating_DemonstratingDangerToSelfOrOthers {
            get {
                return ResourceManager.GetString("InterviewerRating_DemonstratingDangerToSelfOrOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not at All|Slightly symptomatic (patient reports symptoms, no impairment of behavior or function)||Moderately (observable symptoms, no impairment)||Considerably (overt or persistent symptoms suggesting risk of impairment)||Extremely (persistent symptoms with evidence of or report of impairment)|.
        /// </summary>
        public static string InterviewerRating_HasSuicidalThoughts {
            get {
                return ResourceManager.GetString("InterviewerRating_HasSuicidalThoughts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not at All|Slightly symptomatic (patient reports symptoms, no impairment of behavior or function)||Moderately (observable symptoms, no impairment)||Considerably (overt or persistent symptoms suggesting risk of impairment)||Extremely (persistent symptoms with evidence of or report of impairment)|.
        /// </summary>
        public static string InterviewerRating_IndicatingRiskOfHarmToOthers {
            get {
                return ResourceManager.GetString("InterviewerRating_IndicatingRiskOfHarmToOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not at All|Slightly symptomatic (patient reports symptoms, no impairment of behavior or function)||Moderately (observable symptoms, no impairment)||Considerably (overt or persistent symptoms suggesting risk of impairment)||Extremely (persistent symptoms with evidence of or report of impairment)|.
        /// </summary>
        public static string InterviewerRating_IndicatingRiskOfHarmToSelfOrVictimizationByOthers {
            get {
                return ResourceManager.GetString("InterviewerRating_IndicatingRiskOfHarmToSelfOrVictimizationByOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None at All| A little (1-2 visits/week)||Some (&lt;=9 hours/week)||Much (approximately 6 hours/day)||Extreme (24 hours/day)|.
        /// </summary>
        public static string InterviewerRating_LevelOfSupervisionNeededForProtectionFromSelfHarm {
            get {
                return ResourceManager.GetString("InterviewerRating_LevelOfSupervisionNeededForProtectionFromSelfHarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not at All|Slightly (positive history but not under current conditions)||Moderately (positive history and current conditions are simlar to past, but patient has better support system or less stress)||Considerably (history and conditions predict high risk)||Extremely (symptoms evident now)|.
        /// </summary>
        public static string InterviewerRating_LikelihoodOfRecurrenceOfPsychiatricDecompensation {
            get {
                return ResourceManager.GetString("InterviewerRating_LikelihoodOfRecurrenceOfPsychiatricDecompensation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not at All|Slightly symptomatic (patient reports symptoms, no impairment of behavior or function)||Moderately (observable symptoms, no impairment)||Considerably (overt or persistent symptoms suggesting risk of impairment)||Extremely (persistent symptoms with evidence of or report of impairment)|.
        /// </summary>
        public static string InterviewerRating_LimitedInAbilityToContractForSafetyIfRiskOfHarmToSelfOrOthers {
            get {
                return ResourceManager.GetString("InterviewerRating_LimitedInAbilityToContractForSafetyIfRiskOfHarmToSelfOrOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No psychological (i.e. non-substance) problems|Minimal psychological issues (i.e. tolerable grief or depressed mood)||Moderate problems require close outpatient follow-up (e.g. suicidal thoughts)||Considerable problems and risk, especially if uses substances (e.g. history of implusive suicidality, moderate dementia)|| Severe psychological problems (e.g. acutley suicidal, manic, or psychotic)|.
        /// </summary>
        public static string InterviewerRating_PatientNeedForPsychiatricPsychologicalTreatmentRating {
            get {
                return ResourceManager.GetString("InterviewerRating_PatientNeedForPsychiatricPsychologicalTreatmentRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 = No treatment necessary|9 = Treatment needed to intervene on a life threatening situation.
        /// </summary>
        public static string LegalSection_InterviewerRatingPatientNeedForLegalServiceCounseling {
            get {
                return ResourceManager.GetString("LegalSection_InterviewerRatingPatientNeedForLegalServiceCounseling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Activity|Somewhat more than normal activity|Moderately fidgety and restless|||Paces back and forth during most of the interview, or constantly thrashes about||.
        /// </summary>
        public static string MedicalSection_InterviewerObservationOfPatientAgitationLevel {
            get {
                return ResourceManager.GetString("MedicalSection_InterviewerObservationOfPatientAgitationLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No medical (i.e. non-substance) problems|Minimal health issues (e.g. backache, dental disease)||Moderate problems require close outpatient follow-up (e.g. diabetes)||Considerable problems and may need nursing care during day, evening and nights (e.g. chronic pancreatitis)||Severe health problems and may require physician&apos;s change in medical plan at any time (e.g. jaundice, vomiting blood, active seizure)|.
        /// </summary>
        public static string MedicalSection_InterviewerRatingOfPatientNeedForMedicalTreatment {
            get {
                return ResourceManager.GetString("MedicalSection_InterviewerRatingOfPatientNeedForMedicalTreatment", resourceCulture);
            }
        }
    }
}
