//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asam.Ppc.Mvc4.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Permissions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Permissions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Asam.Ppc.Mvc4.Resources.Permissions", typeof(Permissions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Assessment.
        /// </summary>
        public static string assessmentmodule_assessmentedit {
            get {
                return ResourceManager.GetString("assessmentmodule_assessmentedit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Assessment.
        /// </summary>
        public static string assessmentmodule_assessmentview {
            get {
                return ResourceManager.GetString("assessmentmodule_assessmentview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Access.
        /// </summary>
        public static string infrastructuremodule_accessuserinterface {
            get {
                return ResourceManager.GetString("infrastructuremodule_accessuserinterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Organization.
        /// </summary>
        public static string organizationmodule_organizationedit {
            get {
                return ResourceManager.GetString("organizationmodule_organizationedit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Organization.
        /// </summary>
        public static string organizationmodule_organizationview {
            get {
                return ResourceManager.GetString("organizationmodule_organizationview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string organizationmodule_resetpassword {
            get {
                return ResourceManager.GetString("organizationmodule_resetpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Role to Staff.
        /// </summary>
        public static string organizationmodule_staffaddrole {
            get {
                return ResourceManager.GetString("organizationmodule_staffaddrole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Staff Account.
        /// </summary>
        public static string organizationmodule_staffcreateaccount {
            get {
                return ResourceManager.GetString("organizationmodule_staffcreateaccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Staff.
        /// </summary>
        public static string organizationmodule_staffedit {
            get {
                return ResourceManager.GetString("organizationmodule_staffedit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Role From Staff.
        /// </summary>
        public static string organizationmodule_staffremoverole {
            get {
                return ResourceManager.GetString("organizationmodule_staffremoverole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Staff.
        /// </summary>
        public static string organizationmodule_staffview {
            get {
                return ResourceManager.GetString("organizationmodule_staffview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Patient.
        /// </summary>
        public static string patientmodule_patientedit {
            get {
                return ResourceManager.GetString("patientmodule_patientedit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Patient.
        /// </summary>
        public static string patientmodule_patientview {
            get {
                return ResourceManager.GetString("patientmodule_patientview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Permission To Role.
        /// </summary>
        public static string securitynmodule_roleaddpermission {
            get {
                return ResourceManager.GetString("securitynmodule_roleaddpermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Role.
        /// </summary>
        public static string securitynmodule_roleedit {
            get {
                return ResourceManager.GetString("securitynmodule_roleedit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Permission From Role.
        /// </summary>
        public static string securitynmodule_roleremovepermission {
            get {
                return ResourceManager.GetString("securitynmodule_roleremovepermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Role.
        /// </summary>
        public static string securitynmodule_roleview {
            get {
                return ResourceManager.GetString("securitynmodule_roleview", resourceCulture);
            }
        }
    }
}
