CREATE TABLE [ScoringModule].[DiagnosticStatisticalManualOfMentalDisorders_V_Scores] (
    [DiagnosticStatisticalManualOfMentalDisorders_V_ScoresKey]          BIGINT        NOT NULL,
    [Version]                                                           INT           NOT NULL,
    [AlcoholAnyUseScoreIsDependent]                                     BIT           NULL,
    [AlcoholAnyUseScoreSeverityQualifierCount]                          INT           NULL,
    [AlcoholAnyUseScoreHasImminentWithdrawalPotential]                  BIT           NULL,
    [AlcoholAnyUseScoreReceivingOngoingMaintenanceTherapy]              BIT           NULL,
    [AlcoholAnyUseScoreDependenceScoreValue]                            BIGINT        NULL,
    [AlcoholAnyUseScoreDependenceScoreMin]                              BIGINT        NULL,
    [AlcoholAnyUseScoreDependenceScoreMax]                              BIGINT        NULL,
    [AlcoholAnyUseScoreSubstanceUseHistoryHasEverUsed]                  BIT           NULL,
    [AlcoholAnyUseScoreSubstanceUseHistoryLastUsedUnitOfTime]           NVARCHAR (50) NULL,
    [AlcoholAnyUseScoreSubstanceUseHistoryLastUsedValue]                BIGINT        NULL,
    [HeroinScoreIsDependent]                                            BIT           NULL,
    [HeroinScoreSeverityQualifierCount]                                 INT           NULL,
    [HeroinScoreHasImminentWithdrawalPotential]                         BIT           NULL,
    [HeroinScoreReceivingOngoingMaintenanceTherapy]                     BIT           NULL,
    [HeroinScoreDependenceScoreValue]                                   BIGINT        NULL,
    [HeroinScoreDependenceScoreMin]                                     BIGINT        NULL,
    [HeroinScoreDependenceScoreMax]                                     BIGINT        NULL,
    [HeroinScoreSubstanceUseHistoryHasEverUsed]                         BIT           NULL,
    [HeroinScoreSubstanceUseHistoryLastUsedUnitOfTime]                  NVARCHAR (50) NULL,
    [HeroinScoreSubstanceUseHistoryLastUsedValue]                       BIGINT        NULL,
    [MethadoneScoreIsDependent]                                         BIT           NULL,
    [MethadoneScoreSeverityQualifierCount]                              INT           NULL,
    [MethadoneScoreHasImminentWithdrawalPotential]                      BIT           NULL,
    [MethadoneScoreReceivingOngoingMaintenanceTherapy]                  BIT           NULL,
    [MethadoneScoreDependenceScoreValue]                                BIGINT        NULL,
    [MethadoneScoreDependenceScoreMin]                                  BIGINT        NULL,
    [MethadoneScoreDependenceScoreMax]                                  BIGINT        NULL,
    [MethadoneScoreSubstanceUseHistoryHasEverUsed]                      BIT           NULL,
    [MethadoneScoreSubstanceUseHistoryLastUsedUnitOfTime]               NVARCHAR (50) NULL,
    [MethadoneScoreSubstanceUseHistoryLastUsedValue]                    BIGINT        NULL,
    [OtherOpiatesAnalgesicsScoreIsDependent]                            BIT           NULL,
    [OtherOpiatesAnalgesicsScoreSeverityQualifierCount]                 INT           NULL,
    [OtherOpiatesAnalgesicsScoreHasImminentWithdrawalPotential]         BIT           NULL,
    [OtherOpiatesAnalgesicsScoreReceivingOngoingMaintenanceTherapy]     BIT           NULL,
    [OtherOpiatesAnalgesicsScoreDependenceScoreValue]                   BIGINT        NULL,
    [OtherOpiatesAnalgesicsScoreDependenceScoreMin]                     BIGINT        NULL,
    [OtherOpiatesAnalgesicsScoreDependenceScoreMax]                     BIGINT        NULL,
    [OtherOpiatesAnalgesicsScoreSubstanceUseHistoryHasEverUsed]         BIT           NULL,
    [OtherOpiatesAnalgesicsScoreSubstanceUseHistoryLastUsedUnitOfTime]  NVARCHAR (50) NULL,
    [OtherOpiatesAnalgesicsScoreSubstanceUseHistoryLastUsedValue]       BIGINT        NULL,
    [BarbituratesScoreIsDependent]                                      BIT           NULL,
    [BarbituratesScoreSeverityQualifierCount]                           INT           NULL,
    [BarbituratesScoreHasImminentWithdrawalPotential]                   BIT           NULL,
    [BarbituratesScoreReceivingOngoingMaintenanceTherapy]               BIT           NULL,
    [BarbituratesScoreDependenceScoreValue]                             BIGINT        NULL,
    [BarbituratesScoreDependenceScoreMin]                               BIGINT        NULL,
    [BarbituratesScoreDependenceScoreMax]                               BIGINT        NULL,
    [BarbituratesScoreSubstanceUseHistoryHasEverUsed]                   BIT           NULL,
    [BarbituratesScoreSubstanceUseHistoryLastUsedUnitOfTime]            NVARCHAR (50) NULL,
    [BarbituratesScoreSubstanceUseHistoryLastUsedValue]                 BIGINT        NULL,
    [OtherSedativesHypnoticsScoreIsDependent]                           BIT           NULL,
    [OtherSedativesHypnoticsScoreSeverityQualifierCount]                INT           NULL,
    [OtherSedativesHypnoticsScoreHasImminentWithdrawalPotential]        BIT           NULL,
    [OtherSedativesHypnoticsScoreReceivingOngoingMaintenanceTherapy]    BIT           NULL,
    [OtherSedativesHypnoticsScoreDependenceScoreValue]                  BIGINT        NULL,
    [OtherSedativesHypnoticsScoreDependenceScoreMin]                    BIGINT        NULL,
    [OtherSedativesHypnoticsScoreDependenceScoreMax]                    BIGINT        NULL,
    [OtherSedativesHypnoticsScoreSubstanceUseHistoryHasEverUsed]        BIT           NULL,
    [OtherSedativesHypnoticsScoreSubstanceUseHistoryLastUsedUnitOfTime] NVARCHAR (50) NULL,
    [OtherSedativesHypnoticsScoreSubstanceUseHistoryLastUsedValue]      BIGINT        NULL,
    [CocaineScoreIsDependent]                                           BIT           NULL,
    [CocaineScoreSeverityQualifierCount]                                INT           NULL,
    [CocaineScoreHasImminentWithdrawalPotential]                        BIT           NULL,
    [CocaineScoreReceivingOngoingMaintenanceTherapy]                    BIT           NULL,
    [CocaineScoreDependenceScoreValue]                                  BIGINT        NULL,
    [CocaineScoreDependenceScoreMin]                                    BIGINT        NULL,
    [CocaineScoreDependenceScoreMax]                                    BIGINT        NULL,
    [CocaineScoreSubstanceUseHistoryHasEverUsed]                        BIT           NULL,
    [CocaineScoreSubstanceUseHistoryLastUsedUnitOfTime]                 NVARCHAR (50) NULL,
    [CocaineScoreSubstanceUseHistoryLastUsedValue]                      BIGINT        NULL,
    [StimulantsScoreIsDependent]                                        BIT           NULL,
    [StimulantsScoreSeverityQualifierCount]                             INT           NULL,
    [StimulantsScoreHasImminentWithdrawalPotential]                     BIT           NULL,
    [StimulantsScoreReceivingOngoingMaintenanceTherapy]                 BIT           NULL,
    [StimulantsScoreDependenceScoreValue]                               BIGINT        NULL,
    [StimulantsScoreDependenceScoreMin]                                 BIGINT        NULL,
    [StimulantsScoreDependenceScoreMax]                                 BIGINT        NULL,
    [StimulantsScoreSubstanceUseHistoryHasEverUsed]                     BIT           NULL,
    [StimulantsScoreSubstanceUseHistoryLastUsedUnitOfTime]              NVARCHAR (50) NULL,
    [StimulantsScoreSubstanceUseHistoryLastUsedValue]                   BIGINT        NULL,
    [CannabisScoreIsDependent]                                          BIT           NULL,
    [CannabisScoreSeverityQualifierCount]                               INT           NULL,
    [CannabisScoreHasImminentWithdrawalPotential]                       BIT           NULL,
    [CannabisScoreReceivingOngoingMaintenanceTherapy]                   BIT           NULL,
    [CannabisScoreDependenceScoreValue]                                 BIGINT        NULL,
    [CannabisScoreDependenceScoreMin]                                   BIGINT        NULL,
    [CannabisScoreDependenceScoreMax]                                   BIGINT        NULL,
    [CannabisScoreSubstanceUseHistoryHasEverUsed]                       BIT           NULL,
    [CannabisScoreSubstanceUseHistoryLastUsedUnitOfTime]                NVARCHAR (50) NULL,
    [CannabisScoreSubstanceUseHistoryLastUsedValue]                     BIGINT        NULL,
    [HallucinogensScoreIsDependent]                                     BIT           NULL,
    [HallucinogensScoreSeverityQualifierCount]                          INT           NULL,
    [HallucinogensScoreHasImminentWithdrawalPotential]                  BIT           NULL,
    [HallucinogensScoreReceivingOngoingMaintenanceTherapy]              BIT           NULL,
    [HallucinogensScoreDependenceScoreValue]                            BIGINT        NULL,
    [HallucinogensScoreDependenceScoreMin]                              BIGINT        NULL,
    [HallucinogensScoreDependenceScoreMax]                              BIGINT        NULL,
    [HallucinogensScoreSubstanceUseHistoryHasEverUsed]                  BIT           NULL,
    [HallucinogensScoreSubstanceUseHistoryLastUsedUnitOfTime]           NVARCHAR (50) NULL,
    [HallucinogensScoreSubstanceUseHistoryLastUsedValue]                BIGINT        NULL,
    [SolventInhalantsScoreIsDependent]                                  BIT           NULL,
    [SolventInhalantsScoreSeverityQualifierCount]                       INT           NULL,
    [SolventInhalantsScoreHasImminentWithdrawalPotential]               BIT           NULL,
    [SolventInhalantsScoreReceivingOngoingMaintenanceTherapy]           BIT           NULL,
    [SolventInhalantsScoreDependenceScoreValue]                         BIGINT        NULL,
    [SolventInhalantsScoreDependenceScoreMin]                           BIGINT        NULL,
    [SolventInhalantsScoreDependenceScoreMax]                           BIGINT        NULL,
    [SolventInhalantsScoreSubstanceUseHistoryHasEverUsed]               BIT           NULL,
    [SolventInhalantsScoreSubstanceUseHistoryLastUsedUnitOfTime]        NVARCHAR (50) NULL,
    [SolventInhalantsScoreSubstanceUseHistoryLastUsedValue]             BIGINT        NULL,
    [MultiplePerDayScoreIsDependent]                                    BIT           NULL,
    [MultiplePerDayScoreSeverityQualifierCount]                         INT           NULL,
    [MultiplePerDayScoreHasImminentWithdrawalPotential]                 BIT           NULL,
    [MultiplePerDayScoreReceivingOngoingMaintenanceTherapy]             BIT           NULL,
    [MultiplePerDayScoreDependenceScoreValue]                           BIGINT        NULL,
    [MultiplePerDayScoreDependenceScoreMin]                             BIGINT        NULL,
    [MultiplePerDayScoreDependenceScoreMax]                             BIGINT        NULL,
    [MultiplePerDayScoreSubstanceUseHistoryHasEverUsed]                 BIT           NULL,
    [MultiplePerDayScoreSubstanceUseHistoryLastUsedUnitOfTime]          NVARCHAR (50) NULL,
    [MultiplePerDayScoreSubstanceUseHistoryLastUsedValue]               BIGINT        NULL,
    [NicotineTobaccoScoreIsDependent]                                   BIT           NULL,
    [NicotineTobaccoScoreSeverityQualifierCount]                        INT           NULL,
    [NicotineTobaccoScoreHasImminentWithdrawalPotential]                BIT           NULL,
    [NicotineTobaccoScoreReceivingOngoingMaintenanceTherapy]            BIT           NULL,
    [NicotineTobaccoScoreDependenceScoreValue]                          BIGINT        NULL,
    [NicotineTobaccoScoreDependenceScoreMin]                            BIGINT        NULL,
    [NicotineTobaccoScoreDependenceScoreMax]                            BIGINT        NULL,
    [NicotineTobaccoScoreSubstanceUseHistoryHasEverUsed]                BIT           NULL,
    [NicotineTobaccoScoreSubstanceUseHistoryLastUsedUnitOfTime]         NVARCHAR (50) NULL,
    [NicotineTobaccoScoreSubstanceUseHistoryLastUsedValue]              BIGINT        NULL,
    [OtherScoreIsDependent]                                             BIT           NULL,
    [OtherScoreSeverityQualifierCount]                                  INT           NULL,
    [OtherScoreHasImminentWithdrawalPotential]                          BIT           NULL,
    [OtherScoreReceivingOngoingMaintenanceTherapy]                      BIT           NULL,
    [OtherScoreDependenceScoreValue]                                    BIGINT        NULL,
    [OtherScoreDependenceScoreMin]                                      BIGINT        NULL,
    [OtherScoreDependenceScoreMax]                                      BIGINT        NULL,
    [OtherScoreSubstanceUseHistoryHasEverUsed]                          BIT           NULL,
    [OtherScoreSubstanceUseHistoryLastUsedUnitOfTime]                   NVARCHAR (50) NULL,
    [OtherScoreSubstanceUseHistoryLastUsedValue]                        BIGINT        NULL,
    PRIMARY KEY CLUSTERED ([DiagnosticStatisticalManualOfMentalDisorders_V_ScoresKey] ASC)
);



