CREATE TABLE [ScoringModule].[Dimension3EmotionalBehavioralScores] (
    [Dimension3EmotionalBehavioralScoresKey]                                                                            BIGINT NOT NULL,
    [Version]                                                                                                           INT    NOT NULL,
    [CommonScoresHasImmediateMajorDepressionDisorder]                                                                   BIT    NULL,
    [CommonScoresHasCurrentMajorDepressionDisorder]                                                                     BIT    NULL,
    [CommonScoresHasLifetimeMajorDepressionDisorder]                                                                    BIT    NULL,
    [CommonScoresHasImmediateOtherDepressionDisorder]                                                                   BIT    NULL,
    [CommonScoresHasCurrentOtherDepressionDisorder]                                                                     BIT    NULL,
    [CommonScoresHasLifetimeOtherDepressionDisorder]                                                                    BIT    NULL,
    [CommonScoresHasPanicSyndrome]                                                                                      BIT    NULL,
    [CommonScoresHasOtherAnxietySyndrome]                                                                               BIT    NULL,
    [CommonScoresHistoryOfHarmRiskToSelfOthers]                                                                         BIGINT NULL,
    [CommonScoresCurrentHarmRiskToSelfOthers]                                                                           BIGINT NULL,
    [CommonScoresHistoryOfWithdrawalRelatedSymptoms]                                                                    BIT    NULL,
    [CareLevel_0_5_EarlyInterventionScoreHasNoInterferenceFromEmotionalAndBehavioralConditions]                         BIT    NULL,
    [CareLevel_0_5_EarlyInterventionScoreIsMet]                                                                         BIT    NULL,
    [CareLevel_I_OutpatientScoreHasNoInterferenceFromCoexistingMentalDisorder]                                          BIT    NULL,
    [CareLevel_I_OutpatientScoreHasMildSymptomsFromSubstanceUseOrCoexistingMentalDisorder]                              BIT    NULL,
    [CareLevel_I_OutpatientScoreMentalStatusAllowsUnderstandingAndParticipationInTreatment]                             BIT    NULL,
    [CareLevel_I_OutpatientScoreWillNotBeVictimizedAndPosesNoRiskOfHarmToSelfOrOthers]                                  BIT    NULL,
    [CareLevel_I_OutpatientScoreHasSevereMentalDisorderAndAbilityToAccessServices]                                      BIT    NULL,
    [CareLevel_I_OutpatientScoreHasSevereMentalOrSubstanceInducedDisorder]                                              BIT    NULL,
    [CareLevel_I_OutpatientScoreLacksAbilityToUnderstandAndParticipateInTreatment]                                      BIT    NULL,
    [CareLevel_I_OutpatientScorePosesNoRiskOfHarmToSelfOrOthersAndWillNotBeVictimized]                                  BIT    NULL,
    [CareLevel_I_OutpatientScoreIsDualDiagnosisEnhanced]                                                                BIT    NULL,
    [CareLevel_I_OutpatientScoreIsDualDiagnosisCapable]                                                                 BIT    NULL,
    [CareLevel_I_OutpatientScoreIsMet]                                                                                  BIT    NULL,
    [CareLevelOpioidMaintenanceTherapyScoreEmotionalBehavioralProblemsManageableAsOutpatient]                           BIT    NULL,
    [CareLevelOpioidMaintenanceTherapyScoreAbuseOrNeglectOfFamilyRequiresIntensiveOutpatientTreatment]                  BIT    NULL,
    [CareLevelOpioidMaintenanceTherapyScoreRequiresManagementForDiagnosedStableEmotionalProblems]                       BIT    NULL,
    [CareLevelOpioidMaintenanceTherapyScoreNeedsOutpatientTreatmentDueToRiskOfHarmToSelfOrOthers]                       BIT    NULL,
    [CareLevelOpioidMaintenanceTherapyScoreShowsStabilityButNeedsMorePharmacotherapyToStopRelapse]                      BIT    NULL,
    [CareLevelOpioidMaintenanceTherapyScoreIsMet]                                                                       BIT    NULL,
    [CareLevel_II_1_IntensiveOutpatientScoreHasNoNeedForEmotionalBehavioralServices]                                    BIT    NULL,
    [CareLevel_II_1_IntensiveOutpatientScoreAbusesFamilyAndRequiresIntensiveOutpatientTreatment]                        BIT    NULL,
    [CareLevel_II_1_IntensiveOutpatientScoreRequiresManagementForDiagnosedEmotionalProblems]                            BIT    NULL,
    [CareLevel_II_1_IntensiveOutpatientScoreRequiresStabilizationOfDiagnosedEmotionalDisorder]                          BIT    NULL,
    [CareLevel_II_1_IntensiveOutpatientScoreShowsMildRiskOfHarmToSelfOrOthersOrProperty]                                BIT    NULL,
    [CareLevel_II_1_IntensiveOutpatientScoreShowsSignificantRiskOfBeingVictimizedByOthers]                              BIT    NULL,
    [CareLevel_II_1_IntensiveOutpatientScoreIsDualDiagnosisCapable]                                                     BIT    NULL,
    [CareLevel_II_1_IntensiveOutpatientScoreIsDualDiagnosisEnhanced]                                                    BIT    NULL,
    [CareLevel_II_1_IntensiveOutpatientScoreIsMet]                                                                      BIT    NULL,
    [CareLevel_II_5_PartialHospitalizationScoreIsDualDiagnosisEnhanced]                                                 BIT    NULL,
    [CareLevel_II_5_PartialHospitalizationScoreIsDualDiagnosisCapable]                                                  BIT    NULL,
    [CareLevel_II_5_PartialHospitalizationScoreHasNoEmotionalBehavioralConditionsRequiringStabilization]                BIT    NULL,
    [CareLevel_II_5_PartialHospitalizationScoreHasMildToModerateParanoiaOnDiscontinuingDrugOfAbuse]                     BIT    NULL,
    [CareLevel_II_5_PartialHospitalizationScoreHasProblemsButReceivesAdequateSupportFromFamily]                         BIT    NULL,
    [CareLevel_II_5_PartialHospitalizationScoreHasProblemsRequiringSupportiveEnvironmentWithLevelIII_1Care]             BIT    NULL,
    [CareLevel_II_5_PartialHospitalizationScoreCannotMaintainBahavioralStabilityOver48HourPeriod]                       BIT    NULL,
    [CareLevel_II_5_PartialHospitalizationScoreHasCurrentAndHistoricalModeratePsychiatricDecompensation]                BIT    NULL,
    [CareLevel_II_5_PartialHospitalizationScoreLacksCopingSkillsToMaintainSafetyToSelfOthersOrProperty]                 BIT    NULL,
    [CareLevel_II_5_PartialHospitalizationScoreProblemsSeverityIndicatorForPartialHospitalizationDualDiagnosisEnhanced] BIT    NULL,
    [CareLevel_II_5_PartialHospitalizationScoreRequiresPartialHospitalizationOrOutPatientInConjunctionWithLevel3]       BIT    NULL,
    [CareLevel_II_5_PartialHospitalizationScoreIsMet]                                                                   BIT    NULL,
    [CareLevel_III_1_IsDualDiagnosisEnhanced]                                                                           BIT    NULL,
    [CareLevel_III_1_IsDualDiagnosisCapable]                                                                            BIT    NULL,
    [CareLevel_III_1_HasStablePsychiatricConditionAndMinimalProblems]                                                   BIT    NULL,
    [CareLevel_III_1_HasSymptomsInHomeEnvironmentRequiringResidentialTreatment]                                         BIT    NULL,
    [CareLevel_III_1_HasInabilityToMaintain24HourStableBehaviorWithoutAllDaySupport]                                    BIT    NULL,
    [CareLevel_III_1_HasAppropriatePsychiatricCareForEmotionalBehavioralConditions]                                     BIT    NULL,
    [CareLevel_III_1_HasStableMentalStatusToBenefitFromTreatmentAtThisLevel]                                            BIT    NULL,
    [CareLevel_III_1_HasHistoryOfDisordersRequiringMonitoringOfTreatment]                                               BIT    NULL,
    [CareLevel_III_1_MustMonitorPsychiatricSymptomsConcurrentWithAddictionTreatment]                                    BIT    NULL,
    [CareLevel_III_1_IsAbleToSafelyAccessCommunityForWorkAndOtherResources]                                             BIT    NULL,
    [CareLevel_III_1_IsMet]                                                                                             BIT    NULL,
    [CareLevel_III_3_IsDualDiagnosisCapable]                                                                            BIT    NULL,
    [CareLevel_III_3_IsDualDiagnosisEnhanced]                                                                           BIT    NULL,
    [CareLevel_III_3_HasDepressionOrOtherConditionAndNeeds24HourCare]                                                   BIT    NULL,
    [CareLevel_III_3_ExhibitsViolentBehaviorOnIntoxicationAndIsDangerous]                                               BIT    NULL,
    [CareLevel_III_3_HasStressDueToRecentLossesThatImpairDailyActivities]                                               BIT    NULL,
    [CareLevel_III_3_HasSevereConcomitantPersonalityDisorders]                                                          BIT    NULL,
    [CareLevel_III_3_HasSevereFunctionalDeficitsRequiringResidentialTreatment]                                          BIT    NULL,
    [CareLevel_III_3_NeedsLevelIII_3CareDueToMildHarmRiskAndImminentRelapse]                                            BIT    NULL,
    [CareLevel_III_3_HasStableMentalStatusToPermitParticipationInTreatment]                                             BIT    NULL,
    [CareLevel_III_3_NeedsStabilizationOfPsychiatricSymptomsAlongWithTreatment]                                         BIT    NULL,
    [CareLevel_III_3_HasMildRiskOfHarmfulBehaviorsButNoActivePlan]                                                      BIT    NULL,
    [CareLevel_III_3_HasSevereDysfunctionRequiringStabilization]                                                        BIT    NULL,
    [CareLevel_III_3_IsMet]                                                                                             BIT    NULL,
    [CareLevel_III_5_IsDualDiagnosisCapable]                                                                            BIT    NULL,
    [CareLevel_III_5_IsDualDiagnosisEnhanced]                                                                           BIT    NULL,
    [CareLevel_III_5_HasSevereDysfunctionAndCannotControlBehavior]                                                      BIT    NULL,
    [CareLevel_III_5_CannotControlDrugUsageAndInImminentDangerOfRelapse]                                                BIT    NULL,
    [CareLevel_III_5_HasCriminalBehaviorAndLackOfRegardForAuthorityOrOthers]                                            BIT    NULL,
    [CareLevel_III_5_HasSignificantDeficitsButLikelyResponsiveToResidentialTreatment]                                   BIT    NULL,
    [CareLevel_III_5_HasConcomitantDisordersRequiringContinuousBoundarySettingCare]                                     BIT    NULL,
    [CareLevel_III_5_HasStableMentalStatusPermittingParticipationinTreatment]                                           BIT    NULL,
    [CareLevel_III_5_HasHarmRiskAndRequiresImpulseControlManagement]                                                    BIT    NULL,
    [CareLevel_III_5_IsMet]                                                                                             BIT    NULL,
    [CareLevel_III_7_IsDualDiagnosisCapable]                                                                            BIT    NULL,
    [CareLevel_III_7_IsDualDiagnosisEnhanced]                                                                           BIT    NULL,
    [CareLevel_III_7_HasUnstablePsychiatricStateThatInterferesWithRecovery]                                             BIT    NULL,
    [CareLevel_III_7_HasStressDependenceBehaviorRequiresSecureEnvironmentForSelfCare]                                   BIT    NULL,
    [CareLevel_III_7_RequiresActivePsychiatricMonitoringForSignificantDeficits]                                         BIT    NULL,
    [CareLevel_III_7_HasModerateRiskOfHarmToSelfOtherAndPropertyAndRelapsePossible]                                     BIT    NULL,
    [CareLevel_III_7_IsActivelyIntoxicatedWithViolentBehaviorPosingImminentDanger]                                      BIT    NULL,
    [CareLevel_III_7_HasCognitiveProblemsRequiringStabilizationButNoMedicalManagement]                                  BIT    NULL,
    [CareLevel_III_7_HasHistoryOfAndNowHasModerateDecompensationFromStoppingDrugs]                                      BIT    NULL,
    [CareLevel_III_7_HasModerateToHighHarmRiskAndImminentRelapseDanger]                                                 BIT    NULL,
    [CareLevel_III_7_HasSuicidalImpulsesAndPlanButDoesNotNeedOneOnOneSuicideWatch]                                      BIT    NULL,
    [CareLevel_III_7_HasCoOccurringPsychiatricDisorderAndNeedsPsychotropicMeds]                                         BIT    NULL,
    [CareLevel_III_7_HasSevereCoOccurringDisorderAndNeedsIntegratedDualTreatment]                                       BIT    NULL,
    [CareLevel_III_7_IsMet]                                                                                             BIT    NULL,
    [CareLevel_IV_IsDualDiagnosisEnhanced]                                                                              BIT    NULL,
    [CareLevel_IV_HasEmotionalBehavioralComplicationsOfAddictiveDisorder]                                               BIT    NULL,
    [CareLevel_IV_HasConcurrentEmotionalBehavioralIllnessNeedingDailyStabilization]                                     BIT    NULL,
    [CareLevel_IV_ExhibitsBehaviorPosingImminentDangerToSelfOrOthers]                                                   BIT    NULL,
    [CareLevel_IV_HasMentalConfusionPosingImminentDangerToSelfOrOthers]                                                 BIT    NULL,
    [CareLevel_IV_HasCoexistingSeriousDisorderRequiringDifferentialDiagnosis]                                           BIT    NULL,
    [CareLevel_IV_HasExtremeDepressionPosingImminentRiskToPersonalSafety]                                               BIT    NULL,
    [CareLevel_IV_HasImpairedThoughtAndDailyLifePosesRiskToPersonalSafety]                                              BIT    NULL,
    [CareLevel_IV_UseOfAlcoholOrDrugsCausesComplicationsOfPreviousEmotionalProblems]                                    BIT    NULL,
    [CareLevel_IV_IsExperiencingAlteredMentalStatus]                                                                    BIT    NULL,
    PRIMARY KEY CLUSTERED ([Dimension3EmotionalBehavioralScoresKey] ASC)
);






GO


